691:annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#label'),'Iri','Literal').
686:declaration('Class').
560:subClassOf('Class','Class').
553:annotationAssertion(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Rabbit'),'Iri','Literal').
310:annotationAssertion(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Description'),'Iri','Literal').
267:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))).
150:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))).
127:annotationAssertion(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#hasSynonym'),'Iri','Literal').
95:subClassOf('Class',objectSomeValuesFrom('ObjectProperty','Class')).
24:declaration('ObjectProperty').
21:annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment'),'Iri','Literal').
13:subClassOf('Class',objectExactCardinality('1','ObjectProperty','Class')).
13:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class'))))).
7:subClassOf('Class',objectExactCardinality('1','ObjectProperty',objectUnionOf('Class','Class'))).
7:equivalentClasses('Class','Class').
5:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class'))).
5:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class'),objectSomeValuesFrom('ObjectProperty','Class')))).
5:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))))).
5:equivalentClasses('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))).
4:equivalentClasses('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
4:equivalentClasses('Class',objectIntersectionOf('Class',objectExactCardinality('1','ObjectProperty','Class'))).
3:subClassOf('Class',objectMinCardinality('2','ObjectProperty','Class')).
3:subClassOf('Class',objectExactCardinality('1','ObjectProperty',objectUnionOf('Class','Class','Class'))).
3:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class'),objectSomeValuesFrom('ObjectProperty','Class')))))).
3:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class'))))))).
3:subClassOf('Class',objectHasValue('ObjectProperty','NamedIndividual')).
2:subClassOf('Class',objectUnionOf(objectSomeValuesFrom('ObjectProperty','Class'),objectSomeValuesFrom('ObjectProperty','Class'))).
2:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf(objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')),objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
2:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
2:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class','Class'))))).
2:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'),objectSomeValuesFrom('ObjectProperty','Class')))))).
2:subClassOf('Class',objectIntersectionOf(objectUnionOf('Class','Class'),objectComplementOf(objectIntersectionOf('Class','Class')))).
2:equivalentClasses('Class',objectIntersectionOf('Class',objectHasValue('ObjectProperty','NamedIndividual'))).
2:equivalentClasses('Class',objectIntersectionOf('Class',objectComplementOf(objectSomeValuesFrom('ObjectProperty','Class')))).
2:classAssertion('Class','NamedIndividual').
1:annotationAssertion(annotationProperty('http://www.w3.org/2002/07/owl#incompatibleWith'),'Iri','Literal').
1:annotationAssertion(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Definition'),'Iri','Literal').
1:subObjectPropertyOf('ObjectProperty','ObjectProperty').
1:subClassOf('Class',objectMinCardinality('2','ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))).
1:subClassOf('Class',objectUnionOf(objectExactCardinality('1','ObjectProperty',objectUnionOf('Class','Class')),objectExactCardinality('1','ObjectProperty',objectUnionOf('Class','Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))).
1:subClassOf('Class',objectUnionOf(objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class')),objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class')))).
1:subClassOf('Class',objectUnionOf(objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
1:subClassOf('Class',objectUnionOf(objectSomeValuesFrom('ObjectProperty','Class'),objectExactCardinality('1','ObjectProperty',objectUnionOf('Class','Class')))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))),objectAllValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'),objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class'))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'),objectSomeValuesFrom('ObjectProperty','Class')))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class','Class')))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectExactCardinality('1','ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class','Class'),objectComplementOf(objectIntersectionOf('Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class'))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectExactCardinality('1','ObjectProperty','Class')))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class','Class','Class'))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class'),objectComplementOf(objectIntersectionOf('Class','Class'))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectExactCardinality('1','ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class','Class'),objectComplementOf(objectIntersectionOf('Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class')),objectComplementOf(objectIntersectionOf('Class','Class'))))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectExactCardinality('1','ObjectProperty','Class')))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class','Class'))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf(objectUnionOf('Class','Class'),objectComplementOf(objectIntersectionOf('Class','Class'))))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectComplementOf(objectSomeValuesFrom('ObjectProperty','Class'))))))))).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectComplementOf(objectSomeValuesFrom('ObjectProperty','Class'))))))).
1:subClassOf('Class',objectIntersectionOf(objectSomeValuesFrom('ObjectProperty','Class'),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
1:subClassOf('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))).
1:subClassOf('Class',objectAllValuesFrom('ObjectProperty','Class')).
1:equivalentClasses('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class')))))),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectUnionOf('Class','Class')))))).
1:equivalentClasses('Class',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))),objectAllValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
1:equivalentClasses('Class',objectUnionOf('Class','Class')).
1:equivalentClasses('Class',objectIntersectionOf(objectUnionOf('Class','Class'),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))).
1:equivalentClasses('Class',objectIntersectionOf('Class',objectUnionOf(objectIntersectionOf(objectExactCardinality('1','ObjectProperty','Class'),objectExactCardinality('1','ObjectProperty','Class')),objectExactCardinality('2','ObjectProperty','Class')))).
1:equivalentClasses('Class',objectIntersectionOf('Class',objectIntersectionOf(objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class'))))),objectSomeValuesFrom('ObjectProperty',objectIntersectionOf('Class',objectSomeValuesFrom('ObjectProperty','Class')))))).
1:equivalentClasses('Class',objectIntersectionOf('Class','Class')).
1:import('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl').
1:import('http://www.ordnancesurvey.co.uk/ontology/SpatialRelations/v0.2/SpatialRelations.owl').
1:import('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl').
1:import('http://www.ordnancesurvey.co.uk/ontology/NetworkRelations/v0.2/NetworkRelations.owl').
1:import('http://www.ordnancesurvey.co.uk/ontology/MereologicalRelations/v0.2/MereologicalRelations.owl').
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#hasSynonym')).
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Scope')).
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Rabbit')).
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Purpose')).
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Description')).
1:declaration(annotationProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#Definition')).
1:declaration(annotationProperty('http://purl.org/dc/elements/1.1/title')).
1:declaration(annotationProperty('http://purl.org/dc/elements/1.1/rights')).
1:declaration(annotationProperty('http://purl.org/dc/elements/1.1/publisher')).
1:declaration(annotationProperty('http://purl.org/dc/elements/1.1/date')).
1:declaration(annotationProperty('http://purl.org/dc/elements/1.1/creator')).
