class('#Abattoir').
class('#Abbey').
class('#AbbeyChurch').
class('#Academy').
class('#Accommodation').
class('#Address').
class('#Administration').
class('#AirForceBase').
class('#AirTerminalBuilding').
class('#Aircraft').
class('#AircraftHanger').
class('#Airfield').
class('#Airport').
class('#Allotment').
class('#Almshouse').
class('#Ambulance').
class('#AmbulanceStation').
class('#Analysis').
class('#Animal').
class('#AnimalFeed').
class('#AnimalHouse').
class('#Aquarium').
class('#AquaticAnimal').
class('#Archbishop').
class('#Aristocrat').
class('#ArmyReservist').
class('#Arsenal').
class('#Art').
class('#ArtGallery').
class('#Artefact').
class('#Arts').
class('#ArtsCentre').
class('#AstronomicalResearch').
class('#AuctionHouse').
class('#Aviary').
class('#Bakery').
class('#Baking').
class('#Bank').
class('#Barn').
class('#BarrackBlock').
class('#Barracks').
class('#Base').
class('#Bather').
class('#Beach').
class('#BeachEquipment').
class('#BeachHut').
class('#BedAndBreakfast').
class('#Beer').
class('#Bell').
class('#BellHouse').
class('#Berthing').
class('#Bethel').
class('#Bethesda').
class('#Bicycle').
class('#Bird').
class('#Bishop').
class('#BlockOfFlats').
class('#Boat').
class('#BoatHouse').
class('#Bomb').
class('#BombShelter').
class('#Bothy').
class('#BowlingAlley').
class('#BowlingClub').
class('#Bowls').
class('#Brewery').
class('#Brewing').
class('#Bricks').
class('#Brickworks').
class('#Bridge').
class('#Broadcasting').
class('#Building').
class('#Burial').
class('#Burning').
class('#Bus').
class('#BusDepot').
class('#BusStation').
class('#Cadet').
class('#CadetCentre').
class('#CanalFeeder').
class('#CannedProduct').
class('#Cannery').
class('#Capel').
class('#Car').
class('#CarFactory').
class('#CarPark').
class('#CarShowroom').
class('#Care').
class('#CarriageShed').
class('#Castle').
class('#Cat').
class('#CateringFacility').
class('#Cathedral').
class('#Cattery').
class('#Cattle').
class('#CattleMarket').
class('#Cemetery').
class('#CentralGovernment').
class('#Changing').
class('#ChangingRoom').
class('#Chapel').
class('#ChapelOfRest').
class('#CharitableActivity').
class('#Chemical').
class('#ChemicalWorks').
class('#Child').
class('#ChildrensHome').
class('#Christian').
class('#Church').
class('#Cinema').
class('#City').
class('#CityHall').
class('#CivicCentre').
class('#Climber').
class('#ClimbingHut').
class('#Clinic').
class('#Clothes').
class('#Club').
class('#ClubHouse').
class('#ClubMember').
class('#Coach').
class('#CoachStation').
class('#Coast').
class('#Coastguard').
class('#CoastguardLookout').
class('#CoastguardStation').
class('#ColdStorage').
class('#ColdStore').
class('#Collection').
class('#College_Secondary').
class('#College_Secondary_Student').
class('#College_University').
class('#CommunityCentre').
class('#CommunityGroup').
class('#ComprehensiveSchool').
class('#Concert').
class('#ConcertHall').
class('#Conference').
class('#ConferenceCentre').
class('#Construction').
class('#Consumption').
class('#ContainerPort').
class('#ContainerShip').
class('#Control').
class('#ControlTower').
class('#Convalescence').
class('#ConvalescentHome').
class('#Convent').
class('#Corpse').
class('#CouncilEstate').
class('#CouncilOffice').
class('#Country').
class('#CountryClub').
class('#County').
class('#CraftActivity').
class('#Cremation').
class('#Crematorium').
class('#Cricket').
class('#CricketClubMember').
class('#CricketGround').
class('#CricketPavilion').
class('#Crop').
class('#CrownCourt').
class('#CustomsHouse').
class('#CustomsShed').
class('#CycleShed').
class('#DIYSuperstore').
class('#Dairy').
class('#Dam').
class('#DayCentre').
class('#DayTime').
class('#Dean').
class('#Deanery').
class('#Defence').
class('#DefensiveWall').
class('#DeliveryOffice').
class('#DetachedHouse').
class('#Detention').
class('#Dispatch').
class('#Distillery').
class('#Distilling').
class('#Distribution').
class('#Dock').
class('#Docks').
class('#Dockyard').
class('#Dog').
class('#Dove').
class('#Dovecote').
class('#Drainage').
class('#Drawbridge').
class('#Drying').
class('#Ebenezer').
class('#Education').
class('#Egg').
class('#ElderlyPerson').
class('#Electricity').
class('#ElectricitySubStation').
class('#ElectronicCommunications').
class('#EmergencyServiceOrganisation').
class('#EmploymentService').
class('#EndTerraceHouse').
class('#EngineShed').
class('#Entertainment').
class('#Entombment').
class('#EquestrianCentre').
class('#Exercising').
class('#Exhibition').
class('#ExhibitionCentre').
class('#ExoticPlant').
class('#Factory').
class('#Farm').
class('#FarmHouse').
class('#FarmLand').
class('#FarmVehicle').
class('#Farming').
class('#Ferry').
class('#FerryPort').
class('#Film').
class('#FinancialService').
class('#FireEngine').
class('#FireStation').
class('#Fish').
class('#FishMarket').
class('#Flat').
class('#Flower').
class('#Food').
class('#Football').
class('#FootballCentre').
class('#FootballGround').
class('#FootballStadium').
class('#Footprint').
class('#Forge').
class('#Fort').
class('#Foundry').
class('#Fowl').
class('#Freight').
class('#FreightTerminal').
class('#Fruit').
class('#FuneralParlour').
class('#GameBird').
class('#Garage_Private').
class('#Garage_Service').
class('#Garaging').
class('#GardenCentre').
class('#GardenShed').
class('#Garden_Private').
class('#Gardens').
class('#Gas').
class('#GasFlow').
class('#GasGovenor').
class('#GasMeterHouse').
class('#GasTerminal').
class('#GasWorks').
class('#Gate').
class('#Gatehouse').
class('#Gatekeeper').
class('#Generation').
class('#Glass').
class('#GlassFoundry').
class('#Goods').
class('#GoodsShed').
class('#GoodsStation').
class('#GoodsYard').
class('#GospelHall').
class('#GovernmentOffice').
class('#GovernmentOrganisation').
class('#Grain').
class('#GrammarSchool').
class('#Granary').
class('#Grapes').
class('#Greenhouse').
class('#Greyhound').
class('#GreyhoundTrack').
class('#Ground').
class('#Growing').
class('#GuestHouse').
class('#Guildhall').
class('#Gurdwara').
class('#Gym').
class('#Hall').
class('#HallOfResidence').
class('#Hardware').
class('#HealthCare').
class('#HealthCentre').
class('#Hide').
class('#Hiker').
class('#Hill').
class('#HillFort').
class('#HistoricInterest').
class('#HistoricSite').
class('#Holding').
class('#Hops').
class('#Horse').
class('#Hospice').
class('#Hospital').
class('#Hostel').
class('#Hotel').
class('#House').
class('#Housing').
class('#HousingEstate').
class('#HumanConsumption').
class('#Hunter').
class('#HydroelectricPowerStation').
class('#IceRink').
class('#IceSkating').
class('#Icehouse').
class('#IndustrialProcessing').
class('#Infant').
class('#InfantSchool').
class('#InfantSchoolPupil').
class('#InshoreLifeboat').
class('#InshoreRescueBoatStation').
class('#Inspection').
class('#JehovahsWitness').
class('#Jew').
class('#JobCentre').
class('#JuniorSchool').
class('#JuniorSchoolPupil').
class('#Justice').
class('#JuvenileCourt').
class('#Kennels').
class('#KingdomHall').
class('#Kirk').
class('#Kitchen').
class('#Knackery').
class('#Laboratory').
class('#Lairage').
class('#Lake').
class('#Landform').
class('#LawCourt').
class('#LeisureCentre').
class('#Library').
class('#LifeGuardStation').
class('#Lifeboat').
class('#LifeboatHouse').
class('#LifeboatStation').
class('#Lighthouse').
class('#LiveryStables').
class('#Livestock').
class('#Loaning').
class('#LocalAuthority').
class('#Lock').
class('#LockHouse').
class('#LockKeeper').
class('#LockUp').
class('#MagistratesCourt').
class('#Malt').
class('#MaltHouse').
class('#Malting').
class('#Maltings').
class('#Manor').
class('#Manse').
class('#Manufacturing').
class('#Market').
class('#MartelloTower').
class('#Mausoleum').
class('#Meat').
class('#Meeting').
class('#MeetingHouse').
class('#Metal').
class('#MetalProduct').
class('#MilitaryActivity').
class('#MilitaryBase').
class('#MilitaryCamp').
class('#MilitaryPersonnel').
class('#Milk').
class('#Milling').
class('#Minister_Religion').
class('#Minster').
class('#Mission').
class('#Monastery').
class('#Monk').
class('#Moorland').
class('#Mortuary').
class('#Mosque').
class('#MotorBike').
class('#MotorVehicle').
class('#Motorist').
class('#MountainRescueHut').
class('#MountainousArea').
class('#MultiStoreyCarPark').
class('#MunicipalBuilding').
class('#Museum').
class('#Muslim').
class('#Name').
class('#NavalAirStation').
class('#NavalBase').
class('#NavalShip').
class('#NavigationAid').
class('#NuclearPowerStation').
class('#Nun').
class('#Nurse').
class('#NurserySchool').
class('#Nursery_Horticulture').
class('#NursesHome').
class('#NursingHome').
class('#OastHouse').
class('#Observation').
class('#Observatory').
class('#OfficeBuilding').
class('#OfficeWorker').
class('#Oil').
class('#OilRefinery').
class('#OilStorageDepot').
class('#Opera').
class('#OperaHouse').
class('#Oratory').
class('#Ordnance').
class('#Palace').
class('#PalliativeHealthCare').
class('#Pandy').
class('#ParcelOffice').
class('#Parking').
class('#Parson').
class('#Parsonage').
class('#Passenger').
class('#Patient').
class('#Performance').
class('#Person').
class('#PersonalConsumption').
class('#PetrolStation').
class('#Pig').
class('#Pigeon').
class('#PigeonLoft').
class('#Piggery').
class('#Pillbox').
class('#Place').
class('#Plant').
class('#Play').
class('#Playing').
class('#Police').
class('#PoliceBeatOffice').
class('#PoliceHeadquarters').
class('#PoliceHouse').
class('#PoliceStation').
class('#PostOffice').
class('#PostalService').
class('#Poultry').
class('#PoultryHouse').
class('#PowerStation').
class('#Preparation').
class('#PreparatorySchool').
class('#Presbytery').
class('#Priest').
class('#PrimarySchool').
class('#Prior').
class('#Prioress').
class('#Priory').
class('#PrioryChurch').
class('#Prison').
class('#Prisoner').
class('#PrivateSchool').
class('#Processing').
class('#Produce').
class('#Production').
class('#Protection').
class('#Provision').
class('#PsychiatricHospital').
class('#PsychiatricPatient').
class('#PublicConvenience').
class('#PublicEvent').
class('#PublicHouse').
class('#PublicIncinerator').
class('#PublicSchool').
class('#Publication').
class('#Pump').
class('#PumpHouse').
class('#Pumping').
class('#PumpingStation').
class('#Purpose').
class('#Quaker').
class('#RaceHorse').
class('#Racing').
class('#RacingStable').
class('#RadarStation').
class('#RadioSignal').
class('#RadioStation').
class('#Railway').
class('#RailwayCarriage').
class('#RailwayEngine').
class('#RailwayStation').
class('#RawMaterial').
class('#ReadingRoom').
class('#Rearing').
class('#Reception').
class('#Recording').
class('#Recreation').
class('#Rector').
class('#Rectory').
class('#Recycling').
class('#RecyclingCentre').
class('#Refinery').
class('#Refining').
class('#Refreshment').
class('#Refuelling').
class('#RemandCentre').
class('#RemandPrisoner').
class('#Repair').
class('#RepeaterStation').
class('#RescueFacility').
class('#Research').
class('#Reservoir').
class('#Restaurant').
class('#RetailPark').
class('#Riding').
class('#RidingSchool').
class('#River').
class('#Road').
class('#RoadsideServices').
class('#Roof').
class('#Routing').
class('#RoyalFamily').
class('#Rugby').
class('#RugbyGround').
class('#RugbyStadium').
class('#RuralArea').
class('#Sale').
class('#Salem').
class('#SalvationArmyCitadel').
class('#Sanatorium').
class('#Sawmill').
class('#School').
class('#Sea').
class('#Seaman').
class('#SecondarySchool').
class('#SecondarySchoolPupil').
class('#Semi-detachedHouse').
class('#Service').
class('#ServiceStation').
class('#Servicing').
class('#Settlement').
class('#Sewage').
class('#SewagePumpingStation').
class('#Sheep').
class('#SheepMarket').
class('#Shelter').
class('#SheriffsCourt').
class('#Shinty').
class('#ShintyStadium').
class('#Ship').
class('#Shipyard').
class('#ShireHall').
class('#ShootingBox').
class('#Shop').
class('#Shopping').
class('#ShoppingCentre').
class('#Showing').
class('#SignalStation').
class('#Sikh').
class('#SkittleAlley').
class('#Skittles').
class('#Slaughter').
class('#Slaughterhouse').
class('#Smelter').
class('#Smelting').
class('#Smithy').
class('#SmokeHouse').
class('#Smoking').
class('#SocialService').
class('#SocialServiceCentre').
class('#Sorting').
class('#SortingOffice').
class('#SpeedwayStadium').
class('#Spirit').
class('#Sport').
class('#SportsCentre').
class('#SportsGround').
class('#Stables').
class('#Stadium').
class('#Staging').
class('#StateSchool').
class('#StatelyHome').
class('#Steel').
class('#SteelWorks').
class('#Storage').
class('#StorageDepot').
class('#Store').
class('#Storey').
class('#Stream').
class('#Structure').
class('#Student').
class('#Sugar').
class('#SugarRefinery').
class('#Superstore').
class('#Supply').
class('#Surgery').
class('#Surveillance').
class('#Swan').
class('#Swannery').
class('#Swimming').
class('#SwimmingPool').
class('#SwingBridge').
class('#Synagogue').
class('#Tabernacle').
class('#Tannery').
class('#Tanning').
class('#Teaching').
class('#TechnicalCollege').
class('#Teenager').
class('#TelephoneExchange').
class('#TelevisionStation').
class('#Temple').
class('#TenPinBowling').
class('#Tennis').
class('#TennisClub').
class('#TennisCourt').
class('#TerminalBuilding').
class('#TerraceHouse').
class('#TerritorialArmyCentre').
class('#Theatre').
class('#TidalRiver').
class('#TideMill').
class('#Timber').
class('#Tithe').
class('#TitheBarn').
class('#ToiletFacility').
class('#Toll').
class('#TollBooth').
class('#TollHouse').
class('#TollRoad').
class('#TollStation').
class('#TopographicObject').
class('#Tourist').
class('#TouristAttraction').
class('#TouristInformation').
class('#TouristInformationCentre').
class('#Town').
class('#TownHall').
class('#Trading').
class('#Training').
class('#TrainingCentre').
class('#Transfer').
class('#TransmissionStation').
class('#Transport').
class('#Treatment').
class('#UndergroundRailway').
class('#UndergroundStation').
class('#University').
class('#UniversityStudent').
class('#ValveHouse').
class('#Vegetable').
class('#Vehicle').
class('#Velodrome').
class('#VeterinaryCare').
class('#VeterinarySurgery').
class('#Vicar').
class('#Vicarage').
class('#Vineyard').
class('#VisitorCentre').
class('#VulnerablePerson').
class('#Wall').
class('#Warehouse').
class('#Waste').
class('#WasteTransferStation').
class('#Watching').
class('#Water').
class('#WaterFlow').
class('#Watermill').
class('#Waterworks').
class('#Weather').
class('#WeatherStation').
class('#WildfowlCentre').
class('#Wildlife').
class('#Windmill').
class('#Wine').
class('#Winery').
class('#WinterGarden_Building').
class('#WinterGarden_Garden').
class('#Works').
class('#Worship').
class('#YMCAHostel').
class('#YWCAHostel').
class('#YoungOffenderInstitution').
class('#YoungPerson').
class('#YouthClub').
class('#YouthHostel').
class('#Zion').
class('#Zoo').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Footprint').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Holding').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Purpose').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Storage').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Structure').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#TopographicObject').
class('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#Transport').
class('http://www.w3.org/2002/07/owl#Thing').
namedIndividual('#scotland').
namedIndividual('#wales').
objectProperty('#hasAddress').
objectProperty('#hasFootprint').
objectProperty('#hasHistoricInterest').
objectProperty('#hasHistoricPurpose').
objectProperty('#hasName').
objectProperty('#hasStorey').
objectProperty('#isCarriedOutBy').
objectProperty('#isLedBy').
objectProperty('#isLocatedUnder').
objectProperty('#isOperatedBy').
objectProperty('#isOwnedBy').
objectProperty('#operatesDuring').
objectProperty('#requires').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/MereologicalRelations/v0.2/MereologicalRelations.owl#hasPart').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/MereologicalRelations/v0.2/MereologicalRelations.owl#isPartOf').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/NetworkRelations/v0.2/NetworkRelations.owl#isConnectedTo').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#by').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#for').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#from').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#of').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/SpatialRelations/v0.2/SpatialRelations.owl#isLocatedIn').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/SpatialRelations/v0.2/SpatialRelations.owl#isLocatedNear').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/SpatialRelations/v0.2/SpatialRelations.owl#isLocatedOn').
objectProperty('http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#hasPurpose').
