class('#Christian_denomination').
class('#academy_school').
class('#bed-and-breakfast').
class('#bowling_club').
class('#category-A-listed_building').
class('#council_committee_area').
class('#country').
class('#county').
class('#estate').
class('#granite').
class('#guest_house').
class('#house').
class('#place_of_interest').
class('#playing_field').
class('#primary_school').
class('#public_house').
class('#settlement').
class('#skate_park').
class('#town').
class('#village').
dataProperty('#has_approximate_population_of').
dataProperty('#is_dated').
dataProperty('#is_opened_in').
namedIndividual('#Aberdeen').
namedIndividual('#Aberdeenshire').
namedIndividual('#Alehousewells_Primary_School').
namedIndividual('#Bogbeth_Park').
namedIndividual('#Fetternear_Estate').
namedIndividual('#Garioch').
namedIndividual('#Inverurie').
namedIndividual('#John_Fyfe').
namedIndividual('#Kemnay').
namedIndividual('#Kemnay_Academy').
namedIndividual('#Kemnay_Bowling_Club').
namedIndividual('#Kemnay_House').
namedIndividual('#Kemnay_Parish_Church').
namedIndividual('#Kemnay_Primary_School').
namedIndividual('#Kemnay_Quarry').
namedIndividual('#Kemnay_Roman_Catholic_Church').
namedIndividual('#Kemnay_Skate_Park').
namedIndividual('#Kenmay_Quarry').
namedIndividual('#Scotland').
namedIndividual('#St_Anne\'s_Church').
namedIndividual('#The_Bennachie_Lodge').
namedIndividual('#The_Burnett_Arms_Hotel').
namedIndividual('#The_Church_of_Scotland').
namedIndividual('#The_Forth_Railway_Bridge').
namedIndividual('#The_Glasgow_Cenotaph').
namedIndividual('#The_Kemnay_Academy_2014_extension_plan').
namedIndividual('#The_Roman_Catholic_Church').
namedIndividual('#The_Scottish_Episcopal_Church').
namedIndividual('#Westhill').
namedIndividual('#the_River_Don').
objectProperty('#is_constructed_using').
objectProperty('#is_extending').
objectProperty('#is_founded_by').
objectProperty('#is_located_in').
objectProperty('#is_located_on').
objectProperty('#is_more_populous_than').
objectProperty('#is_provided_with').
objectProperty('#is_quarried_in').
objectProperty('#is_west_of').
literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','1830').
literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','2014').
literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','4000').
