classAssertion(class('#Christian_denomination'),namedIndividual('#The_Church_of_Scotland')).
classAssertion(class('#Christian_denomination'),namedIndividual('#The_Roman_Catholic_Church')).
classAssertion(class('#Christian_denomination'),namedIndividual('#The_Scottish_Episcopal_Church')).
classAssertion(class('#academy_school'),namedIndividual('#Kemnay_Academy')).
classAssertion(class('#category-A-listed_building'),namedIndividual('#Kemnay_House')).
classAssertion(class('#council_committee_area'),namedIndividual('#Garioch')).
classAssertion(class('#country'),namedIndividual('#Scotland')).
classAssertion(class('#county'),namedIndividual('#Aberdeenshire')).
classAssertion(class('#estate'),namedIndividual('#Fetternear_Estate')).
classAssertion(class('#place_of_interest'),namedIndividual('#Fetternear_Estate')).
classAssertion(class('#playing_field'),namedIndividual('#Bogbeth_Park')).
classAssertion(class('#primary_school'),namedIndividual('#Alehousewells_Primary_School')).
classAssertion(class('#primary_school'),namedIndividual('#Kemnay_Primary_School')).
classAssertion(class('#skate_park'),namedIndividual('#Kemnay_Skate_Park')).
classAssertion(class('#village'),namedIndividual('#Kemnay')).
classAssertion(dataHasValue(dataProperty('#has_approximate_population_of'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','4000')),namedIndividual('#Kemnay')).
classAssertion(dataHasValue(dataProperty('#is_dated'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','2014')),namedIndividual('#The_Kemnay_Academy_2014_extension_plan')).
classAssertion(objectHasValue(objectProperty('#is_extending'),namedIndividual('#Kemnay_Academy')),namedIndividual('#The_Kemnay_Academy_2014_extension_plan')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Aberdeenshire')),namedIndividual('#Garioch')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Bogbeth_Park')),namedIndividual('#Kemnay_Skate_Park')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Garioch')),namedIndividual('#Kemnay')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Alehousewells_Primary_School')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Bogbeth_Park')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Fetternear_Estate')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Kemnay_Parish_Church')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Kemnay_Primary_School')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#Kemnay_Roman_Catholic_Church')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay')),namedIndividual('#St_Anne\'s_Church')).
classAssertion(objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Scotland')),namedIndividual('#Aberdeenshire')).
classAssertion(objectHasValue(objectProperty('#is_located_on'),namedIndividual('#the_River_Don')),namedIndividual('#Kemnay')).
classAssertion(objectHasValue(objectProperty('#is_more_populous_than'),namedIndividual('#Kemnay')),namedIndividual('#Inverurie')).
classAssertion(objectHasValue(objectProperty('#is_more_populous_than'),namedIndividual('#Kemnay')),namedIndividual('#Westhill')).
classAssertion(objectHasValue(objectProperty('#is_more_populous_than'),namedIndividual('#Westhill')),namedIndividual('#Inverurie')).
classAssertion(objectHasValue(objectProperty('#is_west_of'),namedIndividual('#Aberdeen')),namedIndividual('#Kemnay')).
classAssertion(objectIntersectionOf(class('#bowling_club'),objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay'))),namedIndividual('#Kemnay_Bowling_Club')).
classAssertion(objectIntersectionOf(class('#house'),objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay'))),namedIndividual('#Kemnay_House')).
classAssertion(objectIntersectionOf(class('#public_house'),objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay'))),namedIndividual('#The_Bennachie_Lodge')).
classAssertion(objectIntersectionOf(class('#public_house'),objectHasValue(objectProperty('#is_located_in'),namedIndividual('#Kemnay'))),namedIndividual('#The_Burnett_Arms_Hotel')).
classAssertion(objectIntersectionOf(dataHasValue(dataProperty('#is_opened_in'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#integer','1830')),objectHasValue(objectProperty('#is_founded_by'),namedIndividual('#John_Fyfe'))),namedIndividual('#Kemnay_Quarry')).
classAssertion(objectSomeValuesFrom(objectProperty('#is_constructed_using'),objectIntersectionOf(class('#granite'),objectHasValue(objectProperty('#is_quarried_in'),namedIndividual('#Kenmay_Quarry')))),namedIndividual('#The_Forth_Railway_Bridge')).
classAssertion(objectSomeValuesFrom(objectProperty('#is_constructed_using'),objectIntersectionOf(class('#granite'),objectHasValue(objectProperty('#is_quarried_in'),namedIndividual('#Kenmay_Quarry')))),namedIndividual('#The_Glasgow_Cenotaph')).
classAssertion(objectSomeValuesFrom(objectProperty('#is_provided_with'),class('#bed-and-breakfast')),namedIndividual('#Kemnay')).
classAssertion(objectSomeValuesFrom(objectProperty('#is_provided_with'),class('#guest_house')),namedIndividual('#Kemnay')).
classAssertion(objectSomeValuesFrom(objectProperty('#is_provided_with'),class('#public_house')),namedIndividual('#Kemnay')).
subClassOf(class('#town'),class('#settlement')).
subClassOf(class('#village'),class('#settlement')).
