246:objectPropertyAssertion('ObjectProperty','NamedIndividual','NamedIndividual').
182:classAssertion('Class','NamedIndividual').
74:declaration('Class').
69:subClassOf('Class',objectHasValue('ObjectProperty','NamedIndividual')).
32:equivalentClasses('Class',objectIntersectionOf('Class',objectHasValue('ObjectProperty','NamedIndividual'))).
23:subClassOf('Class',objectAllValuesFrom('ObjectProperty',objectOneOf('NamedIndividual','NamedIndividual'))).
15:subClassOf('Class','Class').
13:equivalentClasses('Class',objectIntersectionOf('Class',objectHasValue('ObjectProperty','NamedIndividual'),objectMaxCardinality('1','ObjectProperty','Class'))).
12:declaration('ObjectProperty').
9:subClassOf('Class',objectMaxCardinality('1','ObjectProperty','Class')).
9:objectPropertyRange('ObjectProperty','Class').
7:equivalentClasses('Class',objectIntersectionOf('Class','Class')).
6:subClassOf('Class',objectExactCardinality('1','ObjectProperty','Class')).
6:objectPropertyDomain('ObjectProperty','Class').
6:functionalObjectProperty('ObjectProperty').
5:subObjectPropertyOf('ObjectProperty','ObjectProperty').
4:differentIndividuals('NamedIndividual','NamedIndividual','NamedIndividual').
4:equivalentClasses('Class',objectOneOf('NamedIndividual','NamedIndividual','NamedIndividual')).
3:differentIndividuals('NamedIndividual','NamedIndividual').
2:annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#label'),'Iri','Literal').
2:inverseObjectProperties('ObjectProperty','ObjectProperty').
2:equivalentClasses('Class',objectIntersectionOf('Class',objectAllValuesFrom('ObjectProperty',objectOneOf('NamedIndividual','NamedIndividual')))).
1:differentIndividuals('NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual').
1:dataPropertyAssertion('DataProperty','NamedIndividual','Literal').
1:annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment'),'Iri','Literal').
1:subClassOf('Class',objectMinCardinality('1','ObjectProperty','Class')).
1:subClassOf('Class',objectSomeValuesFrom('ObjectProperty','Class')).
1:subClassOf('Class',objectAllValuesFrom('ObjectProperty',objectOneOf('NamedIndividual','NamedIndividual','NamedIndividual'))).
1:subClassOf('Class',objectAllValuesFrom('ObjectProperty','Class')).
1:equivalentClasses('Class',objectIntersectionOf('Class',objectAllValuesFrom('ObjectProperty',objectOneOf('NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual','NamedIndividual')),objectMinCardinality('2','ObjectProperty','Class'))).
1:equivalentClasses('Class',objectIntersectionOf('Class','Class',objectHasValue('ObjectProperty','NamedIndividual'))).
1:equivalentClasses('Class',objectUnionOf('Class','Class')).
1:disjointClasses('Class','Class').
1:dataPropertyRange('DataProperty','Datatype').
1:dataPropertyDomain('DataProperty','Class').
1:transitiveObjectProperty('ObjectProperty').
1:symmetricObjectProperty('ObjectProperty').
1:import('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food').
1:declaration('DataProperty').
