declaration(class('#AlsatianWine')).
declaration(class('#AmericanWine')).
declaration(class('#Anjou')).
declaration(class('#Beaujolais')).
declaration(class('#Bordeaux')).
declaration(class('#Burgundy')).
declaration(class('#CabernetFranc')).
declaration(class('#CabernetSauvignon')).
declaration(class('#CaliforniaWine')).
declaration(class('#Chardonnay')).
declaration(class('#CheninBlanc')).
declaration(class('#Chianti')).
declaration(class('#CotesDOr')).
declaration(class('#DessertWine')).
declaration(class('#DryRedWine')).
declaration(class('#DryRiesling')).
declaration(class('#DryWhiteWine')).
declaration(class('#DryWine')).
declaration(class('#EarlyHarvest')).
declaration(class('#FrenchWine')).
declaration(class('#FullBodiedWine')).
declaration(class('#Gamay')).
declaration(class('#GermanWine')).
declaration(class('#IceWine')).
declaration(class('#ItalianWine')).
declaration(class('#LateHarvest')).
declaration(class('#Loire')).
declaration(class('#Margaux')).
declaration(class('#Medoc')).
declaration(class('#Meritage')).
declaration(class('#Merlot')).
declaration(class('#Meursault')).
declaration(class('#Muscadet')).
declaration(class('#Pauillac')).
declaration(class('#PetiteSyrah')).
declaration(class('#PinotBlanc')).
declaration(class('#PinotNoir')).
declaration(class('#Port')).
declaration(class('#RedBordeaux')).
declaration(class('#RedBurgundy')).
declaration(class('#RedTableWine')).
declaration(class('#RedWine')).
declaration(class('#Region')).
declaration(class('#Riesling')).
declaration(class('#RoseWine')).
declaration(class('#Sancerre')).
declaration(class('#Sauternes')).
declaration(class('#SauvignonBlanc')).
declaration(class('#Semillon')).
declaration(class('#SemillonOrSauvignonBlanc')).
declaration(class('#StEmilion')).
declaration(class('#SweetRiesling')).
declaration(class('#SweetWine')).
declaration(class('#TableWine')).
declaration(class('#TexasWine')).
declaration(class('#Tours')).
declaration(class('#Vintage')).
declaration(class('#VintageYear')).
declaration(class('#WhiteBordeaux')).
declaration(class('#WhiteBurgundy')).
declaration(class('#WhiteLoire')).
declaration(class('#WhiteNonSweetWine')).
declaration(class('#WhiteTableWine')).
declaration(class('#WhiteWine')).
declaration(class('#Wine')).
declaration(class('#WineBody')).
declaration(class('#WineColor')).
declaration(class('#WineDescriptor')).
declaration(class('#WineFlavor')).
declaration(class('#WineGrape')).
declaration(class('#WineSugar')).
declaration(class('#WineTaste')).
declaration(class('#Winery')).
declaration(class('#Zinfandel')).
declaration(dataProperty('#yearValue')).
declaration(objectProperty('#adjacentRegion')).
declaration(objectProperty('#hasBody')).
declaration(objectProperty('#hasColor')).
declaration(objectProperty('#hasFlavor')).
declaration(objectProperty('#hasMaker')).
declaration(objectProperty('#hasSugar')).
declaration(objectProperty('#hasVintageYear')).
declaration(objectProperty('#hasWineDescriptor')).
declaration(objectProperty('#locatedIn')).
declaration(objectProperty('#madeFromGrape')).
declaration(objectProperty('#madeIntoWine')).
declaration(objectProperty('#producesWine')).
functionalObjectProperty(objectProperty('#hasBody')).
functionalObjectProperty(objectProperty('#hasColor')).
functionalObjectProperty(objectProperty('#hasFlavor')).
functionalObjectProperty(objectProperty('#hasMaker')).
functionalObjectProperty(objectProperty('#hasSugar')).
functionalObjectProperty(objectProperty('#hasVintageYear')).
import('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food').
symmetricObjectProperty(objectProperty('#adjacentRegion')).
transitiveObjectProperty(objectProperty('#locatedIn')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#CabernetFrancGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#CabernetSauvignonGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#CheninBlancGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Delicate')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Dry')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Full')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Light')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#MalbecGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Medium')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#MerlotGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Moderate')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#OffDry')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#PetiteVerdotGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#PinotBlancGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Red')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Rose')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#SauvignonBlancGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#SemillonGrape')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Strong')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#Sweet')).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),namedIndividual('#White')).
classAssertion(class('#Anjou'),namedIndividual('#RoseDAnjou')).
classAssertion(class('#Beaujolais'),namedIndividual('#ChateauMorgonBeaujolais')).
classAssertion(class('#CabernetFranc'),namedIndividual('#WhitehallLaneCabernetFranc')).
classAssertion(class('#CabernetSauvignon'),namedIndividual('#FormanCabernetSauvignon')).
classAssertion(class('#CabernetSauvignon'),namedIndividual('#MariettaCabernetSauvignon')).
classAssertion(class('#CabernetSauvignon'),namedIndividual('#PageMillWineryCabernetSauvignon')).
classAssertion(class('#CabernetSauvignon'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon')).
classAssertion(class('#Chardonnay'),namedIndividual('#BancroftChardonnay')).
classAssertion(class('#Chardonnay'),namedIndividual('#FormanChardonnay')).
classAssertion(class('#Chardonnay'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay')).
classAssertion(class('#Chardonnay'),namedIndividual('#MountadamChardonnay')).
classAssertion(class('#Chardonnay'),namedIndividual('#PeterMccoyChardonnay')).
classAssertion(class('#CheninBlanc'),namedIndividual('#FoxenCheninBlanc')).
classAssertion(class('#CheninBlanc'),namedIndividual('#VentanaCheninBlanc')).
classAssertion(class('#Chianti'),namedIndividual('#ChiantiClassico')).
classAssertion(class('#CotesDOr'),namedIndividual('#ClosDeVougeotCotesDOr')).
classAssertion(class('#DessertWine'),namedIndividual('#WhitehallLanePrimavera')).
classAssertion(class('#DryRiesling'),namedIndividual('#MountadamRiesling')).
classAssertion(class('#IceWine'),namedIndividual('#SelaksIceWine')).
classAssertion(class('#Margaux'),namedIndividual('#ChateauMargaux')).
classAssertion(class('#Meritage'),namedIndividual('#KathrynKennedyLateral')).
classAssertion(class('#Merlot'),namedIndividual('#GaryFarrellMerlot')).
classAssertion(class('#Merlot'),namedIndividual('#LongridgeMerlot')).
classAssertion(class('#Meursault'),namedIndividual('#ChateauDeMeursaultMeursault')).
classAssertion(class('#Muscadet'),namedIndividual('#SevreEtMaineMuscadet')).
classAssertion(class('#Pauillac'),namedIndividual('#ChateauLafiteRothschildPauillac')).
classAssertion(class('#PetiteSyrah'),namedIndividual('#MariettaPetiteSyrah')).
classAssertion(class('#PetiteSyrah'),namedIndividual('#SeanThackreySiriusPetiteSyrah')).
classAssertion(class('#PinotNoir'),namedIndividual('#LaneTannerPinotNoir')).
classAssertion(class('#PinotNoir'),namedIndividual('#MountEdenVineyardEstatePinotNoir')).
classAssertion(class('#PinotNoir'),namedIndividual('#MountadamPinotNoir')).
classAssertion(class('#Port'),namedIndividual('#TaylorPort')).
classAssertion(class('#RedTableWine'),namedIndividual('#MariettaOldVinesRed')).
classAssertion(class('#Region'),namedIndividual('#AlsaceRegion')).
classAssertion(class('#Region'),namedIndividual('#AnjouRegion')).
classAssertion(class('#Region'),namedIndividual('#ArroyoGrandeRegion')).
classAssertion(class('#Region'),namedIndividual('#AustralianRegion')).
classAssertion(class('#Region'),namedIndividual('#BeaujolaisRegion')).
classAssertion(class('#Region'),namedIndividual('#BordeauxRegion')).
classAssertion(class('#Region'),namedIndividual('#BourgogneRegion')).
classAssertion(class('#Region'),namedIndividual('#CaliforniaRegion')).
classAssertion(class('#Region'),namedIndividual('#CentralCoastRegion')).
classAssertion(class('#Region'),namedIndividual('#CentralTexasRegion')).
classAssertion(class('#Region'),namedIndividual('#ChiantiRegion')).
classAssertion(class('#Region'),namedIndividual('#CotesDOrRegion')).
classAssertion(class('#Region'),namedIndividual('#EdnaValleyRegion')).
classAssertion(class('#Region'),namedIndividual('#FrenchRegion')).
classAssertion(class('#Region'),namedIndividual('#GermanyRegion')).
classAssertion(class('#Region'),namedIndividual('#ItalianRegion')).
classAssertion(class('#Region'),namedIndividual('#LoireRegion')).
classAssertion(class('#Region'),namedIndividual('#MargauxRegion')).
classAssertion(class('#Region'),namedIndividual('#MedocRegion')).
classAssertion(class('#Region'),namedIndividual('#MendocinoRegion')).
classAssertion(class('#Region'),namedIndividual('#MeursaultRegion')).
classAssertion(class('#Region'),namedIndividual('#MuscadetRegion')).
classAssertion(class('#Region'),namedIndividual('#NapaRegion')).
classAssertion(class('#Region'),namedIndividual('#NewZealandRegion')).
classAssertion(class('#Region'),namedIndividual('#PauillacRegion')).
classAssertion(class('#Region'),namedIndividual('#PortugalRegion')).
classAssertion(class('#Region'),namedIndividual('#SancerreRegion')).
classAssertion(class('#Region'),namedIndividual('#SantaBarbaraRegion')).
classAssertion(class('#Region'),namedIndividual('#SantaCruzMountainsRegion')).
classAssertion(class('#Region'),namedIndividual('#SauterneRegion')).
classAssertion(class('#Region'),namedIndividual('#SonomaRegion')).
classAssertion(class('#Region'),namedIndividual('#SouthAustraliaRegion')).
classAssertion(class('#Region'),namedIndividual('#StEmilionRegion')).
classAssertion(class('#Region'),namedIndividual('#TexasRegion')).
classAssertion(class('#Region'),namedIndividual('#ToursRegion')).
classAssertion(class('#Region'),namedIndividual('#USRegion')).
classAssertion(class('#Riesling'),namedIndividual('#CorbansDryWhiteRiesling')).
classAssertion(class('#Sancerre'),namedIndividual('#ClosDeLaPoussieSancerre')).
classAssertion(class('#Sauternes'),namedIndividual('#ChateauDYchemSauterne')).
classAssertion(class('#SauvignonBlanc'),namedIndividual('#CorbansPrivateBinSauvignonBlanc')).
classAssertion(class('#SauvignonBlanc'),namedIndividual('#CorbansSauvignonBlanc')).
classAssertion(class('#SauvignonBlanc'),namedIndividual('#SelaksSauvignonBlanc')).
classAssertion(class('#SauvignonBlanc'),namedIndividual('#StonleighSauvignonBlanc')).
classAssertion(class('#Semillon'),namedIndividual('#CongressSpringsSemillon')).
classAssertion(class('#Semillon'),namedIndividual('#KalinCellarsSemillon')).
classAssertion(class('#StEmilion'),namedIndividual('#ChateauChevalBlancStEmilion')).
classAssertion(class('#SweetRiesling'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling')).
classAssertion(class('#SweetRiesling'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling')).
classAssertion(class('#VintageYear'),namedIndividual('#Year1998')).
classAssertion(class('#WhiteBurgundy'),namedIndividual('#CortonMontrachetWhiteBurgundy')).
classAssertion(class('#WhiteBurgundy'),namedIndividual('#PulignyMontrachetWhiteBurgundy')).
classAssertion(class('#WhiteWine'),namedIndividual('#StGenevieveTexasWhite')).
classAssertion(class('#WineBody'),namedIndividual('#Full')).
classAssertion(class('#WineBody'),namedIndividual('#Light')).
classAssertion(class('#WineBody'),namedIndividual('#Medium')).
classAssertion(class('#WineColor'),namedIndividual('#Red')).
classAssertion(class('#WineColor'),namedIndividual('#Rose')).
classAssertion(class('#WineColor'),namedIndividual('#White')).
classAssertion(class('#WineFlavor'),namedIndividual('#Delicate')).
classAssertion(class('#WineFlavor'),namedIndividual('#Moderate')).
classAssertion(class('#WineFlavor'),namedIndividual('#Strong')).
classAssertion(class('#WineGrape'),namedIndividual('#CabernetFrancGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#CabernetSauvignonGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#ChardonnayGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#CheninBlancGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#GamayGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#MalbecGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#MerlotGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#PetiteSyrahGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#PetiteVerdotGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#PinotBlancGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#PinotNoirGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#RieslingGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#SangioveseGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#SauvignonBlancGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#SemillonGrape')).
classAssertion(class('#WineGrape'),namedIndividual('#ZinfandelGrape')).
classAssertion(class('#WineSugar'),namedIndividual('#Dry')).
classAssertion(class('#WineSugar'),namedIndividual('#OffDry')).
classAssertion(class('#WineSugar'),namedIndividual('#Sweet')).
classAssertion(class('#Winery'),namedIndividual('#Bancroft')).
classAssertion(class('#Winery'),namedIndividual('#Beringer')).
classAssertion(class('#Winery'),namedIndividual('#ChateauChevalBlanc')).
classAssertion(class('#Winery'),namedIndividual('#ChateauDYchem')).
classAssertion(class('#Winery'),namedIndividual('#ChateauDeMeursault')).
classAssertion(class('#Winery'),namedIndividual('#ChateauLafiteRothschild')).
classAssertion(class('#Winery'),namedIndividual('#ChateauMargauxWinery')).
classAssertion(class('#Winery'),namedIndividual('#ChateauMorgon')).
classAssertion(class('#Winery'),namedIndividual('#ClosDeLaPoussie')).
classAssertion(class('#Winery'),namedIndividual('#ClosDeVougeot')).
classAssertion(class('#Winery'),namedIndividual('#CongressSprings')).
classAssertion(class('#Winery'),namedIndividual('#Corbans')).
classAssertion(class('#Winery'),namedIndividual('#CortonMontrachet')).
classAssertion(class('#Winery'),namedIndividual('#Cotturi')).
classAssertion(class('#Winery'),namedIndividual('#DAnjou')).
classAssertion(class('#Winery'),namedIndividual('#Elyse')).
classAssertion(class('#Winery'),namedIndividual('#Forman')).
classAssertion(class('#Winery'),namedIndividual('#Foxen')).
classAssertion(class('#Winery'),namedIndividual('#GaryFarrell')).
classAssertion(class('#Winery'),namedIndividual('#Handley')).
classAssertion(class('#Winery'),namedIndividual('#KalinCellars')).
classAssertion(class('#Winery'),namedIndividual('#KathrynKennedy')).
classAssertion(class('#Winery'),namedIndividual('#LaneTanner')).
classAssertion(class('#Winery'),namedIndividual('#Longridge')).
classAssertion(class('#Winery'),namedIndividual('#Marietta')).
classAssertion(class('#Winery'),namedIndividual('#McGuinnesso')).
classAssertion(class('#Winery'),namedIndividual('#MountEdenVineyard')).
classAssertion(class('#Winery'),namedIndividual('#Mountadam')).
classAssertion(class('#Winery'),namedIndividual('#PageMillWinery')).
classAssertion(class('#Winery'),namedIndividual('#PeterMccoy')).
classAssertion(class('#Winery'),namedIndividual('#PulignyMontrachet')).
classAssertion(class('#Winery'),namedIndividual('#SantaCruzMountainVineyard')).
classAssertion(class('#Winery'),namedIndividual('#SaucelitoCanyon')).
classAssertion(class('#Winery'),namedIndividual('#SchlossRothermel')).
classAssertion(class('#Winery'),namedIndividual('#SchlossVolrad')).
classAssertion(class('#Winery'),namedIndividual('#SeanThackrey')).
classAssertion(class('#Winery'),namedIndividual('#Selaks')).
classAssertion(class('#Winery'),namedIndividual('#SevreEtMaine')).
classAssertion(class('#Winery'),namedIndividual('#StGenevieve')).
classAssertion(class('#Winery'),namedIndividual('#Stonleigh')).
classAssertion(class('#Winery'),namedIndividual('#Taylor')).
classAssertion(class('#Winery'),namedIndividual('#Ventana')).
classAssertion(class('#Winery'),namedIndividual('#WhitehallLane')).
classAssertion(class('#Zinfandel'),namedIndividual('#CotturiZinfandel')).
classAssertion(class('#Zinfandel'),namedIndividual('#ElyseZinfandel')).
classAssertion(class('#Zinfandel'),namedIndividual('#MariettaZinfandel')).
classAssertion(class('#Zinfandel'),namedIndividual('#SaucelitoCanyonZinfandel')).
classAssertion(class('#Zinfandel'),namedIndividual('#SaucelitoCanyonZinfandel1998')).
dataPropertyDomain(dataProperty('#yearValue'),class('#VintageYear')).
dataPropertyRange(dataProperty('#yearValue'),datatype('http://www.w3.org/2001/XMLSchema#positiveInteger')).
differentIndividuals(namedIndividual('#Dry'),namedIndividual('#OffDry')).
differentIndividuals(namedIndividual('#Dry'),namedIndividual('#Sweet')).
differentIndividuals(namedIndividual('#OffDry'),namedIndividual('#Sweet')).
disjointClasses(class('#EarlyHarvest'),class('#LateHarvest')).
equivalentClasses(class('#AlsatianWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#AlsaceRegion')))).
equivalentClasses(class('#AmericanWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#USRegion')))).
equivalentClasses(class('#Anjou'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#AnjouRegion')))).
equivalentClasses(class('#Beaujolais'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BeaujolaisRegion')))).
equivalentClasses(class('#Bordeaux'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BordeauxRegion')))).
equivalentClasses(class('#Burgundy'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BourgogneRegion')))).
equivalentClasses(class('#CabernetFranc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetFrancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CabernetSauvignon'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CaliforniaWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#CaliforniaRegion')))).
equivalentClasses(class('#Chardonnay'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ChardonnayGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CheninBlanc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CheninBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CotesDOr'),objectIntersectionOf(class('#RedBurgundy'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#CotesDOrRegion')))).
equivalentClasses(class('#DryRedWine'),objectIntersectionOf(class('#DryWine'),class('#RedWine'))).
equivalentClasses(class('#DryRiesling'),objectIntersectionOf(class('#Riesling'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')))).
equivalentClasses(class('#DryWhiteWine'),objectIntersectionOf(class('#DryWine'),class('#WhiteWine'))).
equivalentClasses(class('#DryWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')))).
equivalentClasses(class('#FrenchWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#FrenchRegion')))).
equivalentClasses(class('#FullBodiedWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full')))).
equivalentClasses(class('#Gamay'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#GamayGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#GermanWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#GermanyRegion')))).
equivalentClasses(class('#IceWine'),objectIntersectionOf(class('#DessertWine'),class('#LateHarvest'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses(class('#ItalianWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#ItalianRegion')))).
equivalentClasses(class('#Loire'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#LoireRegion')))).
equivalentClasses(class('#Margaux'),objectIntersectionOf(class('#Medoc'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MargauxRegion')))).
equivalentClasses(class('#Medoc'),objectIntersectionOf(class('#Bordeaux'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MedocRegion')))).
equivalentClasses(class('#Meritage'),objectIntersectionOf(class('#Wine'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#CabernetFrancGrape'),namedIndividual('#PetiteVerdotGrape'),namedIndividual('#MalbecGrape'),namedIndividual('#MerlotGrape'))),objectMinCardinality('2',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Merlot'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#MerlotGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Meursault'),objectIntersectionOf(class('#WhiteBurgundy'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MeursaultRegion')))).
equivalentClasses(class('#Muscadet'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MuscadetRegion')))).
equivalentClasses(class('#Pauillac'),objectIntersectionOf(class('#Medoc'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#PauillacRegion')))).
equivalentClasses(class('#PetiteSyrah'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PetiteSyrahGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#PinotBlanc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#PinotNoir'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotNoirGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#RedBordeaux'),objectIntersectionOf(class('#Bordeaux'),class('#RedWine'))).
equivalentClasses(class('#RedBurgundy'),objectIntersectionOf(class('#Burgundy'),class('#RedWine'))).
equivalentClasses(class('#RedTableWine'),objectIntersectionOf(class('#TableWine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')))).
equivalentClasses(class('#RedWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')))).
equivalentClasses(class('#Riesling'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#RieslingGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#RoseWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Rose')))).
equivalentClasses(class('#Sancerre'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#SancerreRegion')))).
equivalentClasses(class('#SauvignonBlanc'),objectIntersectionOf(class('#SemillonOrSauvignonBlanc'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SauvignonBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Semillon'),objectIntersectionOf(class('#SemillonOrSauvignonBlanc'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SemillonGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#SemillonOrSauvignonBlanc'),objectIntersectionOf(class('#Wine'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#SemillonGrape'),namedIndividual('#SauvignonBlancGrape'))))).
equivalentClasses(class('#StEmilion'),objectIntersectionOf(class('#Bordeaux'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#StEmilionRegion')))).
equivalentClasses(class('#SweetRiesling'),objectIntersectionOf(class('#Riesling'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet')))).
equivalentClasses(class('#SweetWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet')))).
equivalentClasses(class('#TableWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')))).
equivalentClasses(class('#TexasWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#TexasRegion')))).
equivalentClasses(class('#Tours'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#ToursRegion')))).
equivalentClasses(class('#WhiteBordeaux'),objectIntersectionOf(class('#Bordeaux'),class('#WhiteWine'))).
equivalentClasses(class('#WhiteBurgundy'),objectIntersectionOf(class('#Burgundy'),class('#WhiteWine'))).
equivalentClasses(class('#WhiteLoire'),objectIntersectionOf(class('#Loire'),class('#WhiteWine'))).
equivalentClasses(class('#WhiteNonSweetWine'),objectIntersectionOf(class('#WhiteWine'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry'))))).
equivalentClasses(class('#WhiteTableWine'),objectIntersectionOf(class('#TableWine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses(class('#WhiteWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses(class('#WineBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'),namedIndividual('#Light'))).
equivalentClasses(class('#WineColor'),objectOneOf(namedIndividual('#Rose'),namedIndividual('#White'),namedIndividual('#Red'))).
equivalentClasses(class('#WineDescriptor'),objectUnionOf(class('#WineColor'),class('#WineTaste'))).
equivalentClasses(class('#WineFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Delicate'),namedIndividual('#Strong'))).
equivalentClasses(class('#WineSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Sweet'),namedIndividual('#Dry'))).
equivalentClasses(class('#Zinfandel'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ZinfandelGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
inverseObjectProperties(objectProperty('#madeIntoWine'),objectProperty('#madeFromGrape')).
inverseObjectProperties(objectProperty('#producesWine'),objectProperty('#hasMaker')).
objectPropertyDomain(objectProperty('#adjacentRegion'),class('#Region')).
objectPropertyDomain(objectProperty('#hasColor'),class('#Wine')).
objectPropertyDomain(objectProperty('#hasVintageYear'),class('#Vintage')).
objectPropertyDomain(objectProperty('#hasWineDescriptor'),class('#Wine')).
objectPropertyDomain(objectProperty('#locatedIn'),class('http://www.w3.org/2002/07/owl#Thing')).
objectPropertyDomain(objectProperty('#madeFromGrape'),class('#Wine')).
objectPropertyRange(objectProperty('#adjacentRegion'),class('#Region')).
objectPropertyRange(objectProperty('#hasBody'),class('#WineBody')).
objectPropertyRange(objectProperty('#hasColor'),class('#WineColor')).
objectPropertyRange(objectProperty('#hasFlavor'),class('#WineFlavor')).
objectPropertyRange(objectProperty('#hasSugar'),class('#WineSugar')).
objectPropertyRange(objectProperty('#hasVintageYear'),class('#VintageYear')).
objectPropertyRange(objectProperty('#hasWineDescriptor'),class('#WineDescriptor')).
objectPropertyRange(objectProperty('#locatedIn'),class('#Region')).
objectPropertyRange(objectProperty('#madeFromGrape'),class('#WineGrape')).
subClassOf(class('#Anjou'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light'))).
subClassOf(class('#Anjou'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Rose'))).
subClassOf(class('#Anjou'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#Anjou'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#OffDry'))).
subClassOf(class('#Beaujolais'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light'))).
subClassOf(class('#Beaujolais'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Beaujolais'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#Beaujolais'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Beaujolais'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#GamayGrape'))).
subClassOf(class('#Beaujolais'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Burgundy'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#CabernetFranc'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium'))).
subClassOf(class('#CabernetFranc'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#CabernetFranc'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))).
subClassOf(class('#CabernetFranc'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#CabernetSauvignon'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#CabernetSauvignon'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#CabernetSauvignon'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#CabernetSauvignon'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Chardonnay'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#Chardonnay'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#Chardonnay'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#CheninBlanc'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#CheninBlanc'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry')))).
subClassOf(class('#CheninBlanc'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#CheninBlanc'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))).
subClassOf(class('#Chianti'),class('#ItalianWine')).
subClassOf(class('#Chianti'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Medium'),namedIndividual('#Light')))).
subClassOf(class('#Chianti'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Chianti'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))).
subClassOf(class('#Chianti'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Chianti'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#ChiantiRegion'))).
subClassOf(class('#Chianti'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SangioveseGrape'))).
subClassOf(class('#CotesDOr'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))).
subClassOf(class('#DessertWine'),class('#Wine')).
subClassOf(class('#DessertWine'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Sweet')))).
subClassOf(class('#DryRiesling'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Medium'),namedIndividual('#Light')))).
subClassOf(class('#DryRiesling'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#DryRiesling'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#EarlyHarvest'),class('#Wine')).
subClassOf(class('#EarlyHarvest'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry')))).
subClassOf(class('#IceWine'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#IceWine'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#LateHarvest'),class('#Wine')).
subClassOf(class('#LateHarvest'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#LateHarvest'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet'))).
subClassOf(class('#Margaux'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#Margaux'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#MerlotGrape'))).
subClassOf(class('#Margaux'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Medoc'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Medoc'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Meritage'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Merlot'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Medium'),namedIndividual('#Light')))).
subClassOf(class('#Merlot'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Delicate')))).
subClassOf(class('#Merlot'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Merlot'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Meursault'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full'))).
subClassOf(class('#Muscadet'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light'))).
subClassOf(class('#Muscadet'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#Muscadet'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#Muscadet'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotBlancGrape'))).
subClassOf(class('#Muscadet'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Pauillac'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full'))).
subClassOf(class('#Pauillac'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong'))).
subClassOf(class('#Pauillac'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape'))).
subClassOf(class('#Pauillac'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#PetiteSyrah'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#PetiteSyrah'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#PetiteSyrah'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#PetiteSyrah'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf(class('#PinotBlanc'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#PinotNoir'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Port'),class('#RedWine')).
subClassOf(class('#Port'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full'))).
subClassOf(class('#Port'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong'))).
subClassOf(class('#Port'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet'))).
subClassOf(class('#Port'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#PortugalRegion'))).
subClassOf(class('#RedBordeaux'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#MerlotGrape')))).
subClassOf(class('#RedBurgundy'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotNoirGrape'))).
subClassOf(class('#RedBurgundy'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Riesling'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#Sancerre'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium'))).
subClassOf(class('#Sancerre'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf(class('#Sancerre'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#OffDry'))).
subClassOf(class('#Sancerre'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SauvignonBlancGrape'))).
subClassOf(class('#Sancerre'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Sauternes'),class('#Bordeaux')).
subClassOf(class('#Sauternes'),class('#LateHarvest')).
subClassOf(class('#Sauternes'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium'))).
subClassOf(class('#Sauternes'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#Sauternes'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#SauterneRegion'))).
subClassOf(class('#SemillonOrSauvignonBlanc'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#SemillonOrSauvignonBlanc'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf(class('#StEmilion'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#StEmilion'),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong'))).
subClassOf(class('#StEmilion'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape'))).
subClassOf(class('#StEmilion'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#SweetRiesling'),class('#DessertWine')).
subClassOf(class('#SweetRiesling'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#SweetRiesling'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full'))).
subClassOf(class('#Tours'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CheninBlancGrape'))).
subClassOf(class('#Tours'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Vintage'),objectExactCardinality('1',objectProperty('#hasVintageYear'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#WhiteBordeaux'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#SemillonGrape'),namedIndividual('#SauvignonBlancGrape')))).
subClassOf(class('#WhiteBurgundy'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ChardonnayGrape'))).
subClassOf(class('#WhiteBurgundy'),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#WhiteLoire'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#PinotBlancGrape'),namedIndividual('#CheninBlancGrape'),namedIndividual('#SauvignonBlancGrape')))).
subClassOf(class('#Wine'),class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#PotableLiquid')).
subClassOf(class('#Wine'),objectAllValuesFrom(objectProperty('#hasMaker'),class('#Winery'))).
subClassOf(class('#Wine'),objectExactCardinality('1',objectProperty('#hasBody'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectExactCardinality('1',objectProperty('#hasColor'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectExactCardinality('1',objectProperty('#hasFlavor'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectExactCardinality('1',objectProperty('#hasMaker'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectExactCardinality('1',objectProperty('#hasSugar'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectMinCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectSomeValuesFrom(objectProperty('#locatedIn'),class('#Region'))).
subClassOf(class('#WineBody'),class('#WineTaste')).
subClassOf(class('#WineColor'),class('#WineDescriptor')).
subClassOf(class('#WineFlavor'),class('#WineTaste')).
subClassOf(class('#WineGrape'),class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#Grape')).
subClassOf(class('#WineSugar'),class('#WineTaste')).
subClassOf(class('#WineTaste'),class('#WineDescriptor')).
subClassOf(class('#Zinfandel'),objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf(class('#Zinfandel'),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf(class('#Zinfandel'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf(class('#Zinfandel'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subObjectPropertyOf(objectProperty('#hasBody'),objectProperty('#hasWineDescriptor')).
subObjectPropertyOf(objectProperty('#hasColor'),objectProperty('#hasWineDescriptor')).
subObjectPropertyOf(objectProperty('#hasFlavor'),objectProperty('#hasWineDescriptor')).
subObjectPropertyOf(objectProperty('#hasSugar'),objectProperty('#hasWineDescriptor')).
subObjectPropertyOf(objectProperty('#madeFromGrape'),objectProperty('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#madeFromFruit')).
annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment'),iri('#WineDescriptor'),literal('Made WineDescriptor unionType of tastes and color')).
annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#label'),iri('#Wine'),literal('xml:lang'=en,wine)).
annotationAssertion(annotationProperty('http://www.w3.org/2000/01/rdf-schema#label'),iri('#Wine'),literal('xml:lang'=fr,vin)).
dataPropertyAssertion(dataProperty('#yearValue'),namedIndividual('#Year1998'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#positiveInteger','1998')).
differentIndividuals(namedIndividual('#Delicate'),namedIndividual('#Moderate'),namedIndividual('#Strong')).
differentIndividuals(namedIndividual('#Dry'),namedIndividual('#OffDry'),namedIndividual('#Sweet')).
differentIndividuals(namedIndividual('#Full'),namedIndividual('#Light'),namedIndividual('#Medium')).
differentIndividuals(namedIndividual('#Red'),namedIndividual('#Rose'),namedIndividual('#White')).
objectPropertyAssertion(objectProperty('#adjacentRegion'),namedIndividual('#MendocinoRegion'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#BancroftChardonnay'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#ChiantiClassico'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#CotturiZinfandel'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#ElyseZinfandel'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#FormanChardonnay'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#KalinCellarsSemillon'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#KathrynKennedyLateral'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#Light')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#LongridgeMerlot'),namedIndividual('#Light')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MariettaZinfandel'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MountadamChardonnay'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#MountadamRiesling'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#PulignyMontrachetWhiteBurgundy'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SelaksIceWine'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#SelaksSauvignonBlanc'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),namedIndividual('#WhitehallLanePrimavera'),namedIndividual('#Light')).
objectPropertyAssertion(objectProperty('#hasColor'),namedIndividual('#SelaksIceWine'),namedIndividual('#White')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#BancroftChardonnay'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#ChateauDeMeursaultMeursault'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#CotturiZinfandel'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#ElyseZinfandel'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#FormanChardonnay'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#KalinCellarsSemillon'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#KathrynKennedyLateral'),namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#LongridgeMerlot'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MariettaZinfandel'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MountadamChardonnay'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#MountadamRiesling'),namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#PulignyMontrachetWhiteBurgundy'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SelaksIceWine'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#SelaksSauvignonBlanc'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),namedIndividual('#WhitehallLanePrimavera'),namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#BancroftChardonnay'),namedIndividual('#Bancroft')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauChevalBlancStEmilion'),namedIndividual('#ChateauChevalBlanc')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#ChateauDYchem')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauDeMeursaultMeursault'),namedIndividual('#ChateauDeMeursault')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauLafiteRothschildPauillac'),namedIndividual('#ChateauLafiteRothschild')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauMargaux'),namedIndividual('#ChateauMargauxWinery')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauMorgonBeaujolais'),namedIndividual('#ChateauMorgon')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChiantiClassico'),namedIndividual('#McGuinnesso')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ClosDeLaPoussieSancerre'),namedIndividual('#ClosDeLaPoussie')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ClosDeVougeotCotesDOr'),namedIndividual('#ClosDeVougeot')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#CongressSprings')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#Corbans')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#Corbans')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#Corbans')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#CortonMontrachet')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CotturiZinfandel'),namedIndividual('#Cotturi')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ElyseZinfandel'),namedIndividual('#Elyse')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#Forman')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#FormanChardonnay'),namedIndividual('#Forman')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#Foxen')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#GaryFarrell')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#KalinCellarsSemillon'),namedIndividual('#KalinCellars')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#KathrynKennedyLateral'),namedIndividual('#KathrynKennedy')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#LaneTanner')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#LongridgeMerlot'),namedIndividual('#Longridge')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#Marietta')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#Marietta')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#Marietta')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MariettaZinfandel'),namedIndividual('#Marietta')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#MountEdenVineyard')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#MountEdenVineyard')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MountadamChardonnay'),namedIndividual('#Mountadam')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#Mountadam')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#MountadamRiesling'),namedIndividual('#Mountadam')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#PageMillWinery')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#PeterMccoy')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PulignyMontrachetWhiteBurgundy'),namedIndividual('#PulignyMontrachet')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#RoseDAnjou'),namedIndividual('#DAnjou')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#SantaCruzMountainVineyard')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#SaucelitoCanyon')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#SaucelitoCanyon')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#SchlossRothermel')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#SchlossVolrad')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#SeanThackrey')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SelaksIceWine'),namedIndividual('#Selaks')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SelaksSauvignonBlanc'),namedIndividual('#Selaks')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SevreEtMaineMuscadet'),namedIndividual('#SevreEtMaine')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#StGenevieve')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#Stonleigh')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#TaylorPort'),namedIndividual('#Taylor')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#Ventana')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#WhitehallLane')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#BancroftChardonnay'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#OffDry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#CotturiZinfandel'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#ElyseZinfandel'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#FormanChardonnay'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#KalinCellarsSemillon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#KathrynKennedyLateral'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#LongridgeMerlot'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MariettaZinfandel'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MountadamChardonnay'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#MountadamRiesling'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#PulignyMontrachetWhiteBurgundy'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#Sweet')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#Sweet')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#SelaksSauvignonBlanc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#OffDry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),namedIndividual('#WhitehallLanePrimavera'),namedIndividual('#Sweet')).
objectPropertyAssertion(objectProperty('#hasVintageYear'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#Year1998')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#AlsaceRegion'),namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#AnjouRegion'),namedIndividual('#LoireRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#ArroyoGrandeRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#BancroftChardonnay'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#BeaujolaisRegion'),namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#BordeauxRegion'),namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#BourgogneRegion'),namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CaliforniaRegion'),namedIndividual('#USRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CentralCoastRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CentralTexasRegion'),namedIndividual('#TexasRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#ChiantiRegion'),namedIndividual('#ItalianRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CotesDOrRegion'),namedIndividual('#BourgogneRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CotturiZinfandel'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#EdnaValleyRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#ElyseZinfandel'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#FormanChardonnay'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#SantaBarbaraRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#SantaBarbaraRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#LoireRegion'),namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#LongridgeMerlot'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MargauxRegion'),namedIndividual('#MedocRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MariettaZinfandel'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MedocRegion'),namedIndividual('#BordeauxRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MendocinoRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MeursaultRegion'),namedIndividual('#BourgogneRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#EdnaValleyRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#EdnaValleyRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MountadamChardonnay'),namedIndividual('#SouthAustraliaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#SouthAustraliaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MountadamRiesling'),namedIndividual('#SouthAustraliaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#MuscadetRegion'),namedIndividual('#LoireRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#NapaRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#PauillacRegion'),namedIndividual('#MedocRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SancerreRegion'),namedIndividual('#LoireRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SantaBarbaraRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#SantaCruzMountainsRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SantaCruzMountainsRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#ArroyoGrandeRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#ArroyoGrandeRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SauterneRegion'),namedIndividual('#BordeauxRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#GermanyRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#GermanyRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SelaksIceWine'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SelaksSauvignonBlanc'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SonomaRegion'),namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SouthAustraliaRegion'),namedIndividual('#AustralianRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#StEmilionRegion'),namedIndividual('#BordeauxRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#CentralTexasRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#TexasRegion'),namedIndividual('#USRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#ToursRegion'),namedIndividual('#LoireRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#CentralCoastRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#WhitehallLanePrimavera'),namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#madeFromGrape'),namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#SauvignonBlancGrape')).
objectPropertyAssertion(objectProperty('#madeFromGrape'),namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#SemillonGrape')).
differentIndividuals(namedIndividual('#Bancroft'),namedIndividual('#ChateauChevalBlanc'),namedIndividual('#ChateauDYchem'),namedIndividual('#ChateauDeMeursault'),namedIndividual('#ChateauLafiteRothschild'),namedIndividual('#ChateauMargauxWinery'),namedIndividual('#ChateauMorgon'),namedIndividual('#ClosDeLaPoussie'),namedIndividual('#ClosDeVougeot'),namedIndividual('#CongressSprings'),namedIndividual('#Corbans'),namedIndividual('#CortonMontrachet'),namedIndividual('#Cotturi'),namedIndividual('#DAnjou'),namedIndividual('#Elyse'),namedIndividual('#Forman'),namedIndividual('#Foxen'),namedIndividual('#GaryFarrell'),namedIndividual('#KalinCellars'),namedIndividual('#KathrynKennedy'),namedIndividual('#LaneTanner'),namedIndividual('#Longridge'),namedIndividual('#Marietta'),namedIndividual('#McGuinnesso'),namedIndividual('#MountEdenVineyard'),namedIndividual('#Mountadam'),namedIndividual('#PageMillWinery'),namedIndividual('#PeterMccoy'),namedIndividual('#PulignyMontrachet'),namedIndividual('#SantaCruzMountainVineyard'),namedIndividual('#SaucelitoCanyon'),namedIndividual('#SchlossRothermel'),namedIndividual('#SchlossVolrad'),namedIndividual('#SeanThackrey'),namedIndividual('#Selaks'),namedIndividual('#SevreEtMaine'),namedIndividual('#StGenevieve'),namedIndividual('#Stonleigh'),namedIndividual('#Taylor'),namedIndividual('#Ventana'),namedIndividual('#WhitehallLane')).
