objectPropertyAssertion(objectProperty('#adjacentRegion'),namedIndividual('#MendocinoRegion'),namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#hasBody'),[namedIndividual('#BancroftChardonnay'),namedIndividual('#ChiantiClassico'),namedIndividual('#CongressSpringsSemillon'),numberOfElements('25')],namedIndividual('#Medium')).
objectPropertyAssertion(objectProperty('#hasBody'),[namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#CotturiZinfandel'),numberOfElements('13')],namedIndividual('#Full')).
objectPropertyAssertion(objectProperty('#hasBody'),[namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#LongridgeMerlot'),namedIndividual('#WhitehallLanePrimavera')],namedIndividual('#Light')).
objectPropertyAssertion(objectProperty('#hasColor'),namedIndividual('#SelaksIceWine'),namedIndividual('#White')).
objectPropertyAssertion(objectProperty('#hasFlavor'),[namedIndividual('#BancroftChardonnay'),namedIndividual('#ChateauDeMeursaultMeursault'),namedIndividual('#CongressSpringsSemillon'),numberOfElements('26')],namedIndividual('#Moderate')).
objectPropertyAssertion(objectProperty('#hasFlavor'),[namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#CorbansSauvignonBlanc'),numberOfElements('12')],namedIndividual('#Strong')).
objectPropertyAssertion(objectProperty('#hasFlavor'),[namedIndividual('#KathrynKennedyLateral'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#MountadamRiesling'),numberOfElements('5')],namedIndividual('#Delicate')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#BancroftChardonnay'),namedIndividual('#Bancroft')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauChevalBlancStEmilion'),namedIndividual('#ChateauChevalBlanc')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauDYchemSauterne'),namedIndividual('#ChateauDYchem')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauDeMeursaultMeursault'),namedIndividual('#ChateauDeMeursault')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauLafiteRothschildPauillac'),namedIndividual('#ChateauLafiteRothschild')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauMargaux'),namedIndividual('#ChateauMargauxWinery')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChateauMorgonBeaujolais'),namedIndividual('#ChateauMorgon')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ChiantiClassico'),namedIndividual('#McGuinnesso')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ClosDeLaPoussieSancerre'),namedIndividual('#ClosDeLaPoussie')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ClosDeVougeotCotesDOr'),namedIndividual('#ClosDeVougeot')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#CongressSprings')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#CortonMontrachet')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#CotturiZinfandel'),namedIndividual('#Cotturi')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#ElyseZinfandel'),namedIndividual('#Elyse')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#FoxenCheninBlanc'),namedIndividual('#Foxen')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#GaryFarrell')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#KalinCellarsSemillon'),namedIndividual('#KalinCellars')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#KathrynKennedyLateral'),namedIndividual('#KathrynKennedy')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#LaneTanner')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#LongridgeMerlot'),namedIndividual('#Longridge')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PageMillWineryCabernetSauvignon'),namedIndividual('#PageMillWinery')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PeterMccoyChardonnay'),namedIndividual('#PeterMccoy')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#PulignyMontrachetWhiteBurgundy'),namedIndividual('#PulignyMontrachet')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#RoseDAnjou'),namedIndividual('#DAnjou')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#SantaCruzMountainVineyard')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#SchlossRothermel')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#SchlossVolrad')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SeanThackreySiriusPetiteSyrah'),namedIndividual('#SeanThackrey')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#SevreEtMaineMuscadet'),namedIndividual('#SevreEtMaine')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#StGenevieve')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#StonleighSauvignonBlanc'),namedIndividual('#Stonleigh')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#TaylorPort'),namedIndividual('#Taylor')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#Ventana')).
objectPropertyAssertion(objectProperty('#hasMaker'),namedIndividual('#WhitehallLaneCabernetFranc'),namedIndividual('#WhitehallLane')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#CorbansSauvignonBlanc')],namedIndividual('#Corbans')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#FormanChardonnay')],namedIndividual('#Forman')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#MariettaOldVinesRed'),namedIndividual('#MariettaPetiteSyrah'),numberOfElements('4')],namedIndividual('#Marietta')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#MountEdenVineyardEstatePinotNoir')],namedIndividual('#MountEdenVineyard')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#MountadamChardonnay'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#MountadamRiesling')],namedIndividual('#Mountadam')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#SaucelitoCanyonZinfandel1998')],namedIndividual('#SaucelitoCanyon')).
objectPropertyAssertion(objectProperty('#hasMaker'),[namedIndividual('#SelaksIceWine'),namedIndividual('#SelaksSauvignonBlanc')],namedIndividual('#Selaks')).
objectPropertyAssertion(objectProperty('#hasSugar'),[namedIndividual('#BancroftChardonnay'),namedIndividual('#CongressSpringsSemillon'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),numberOfElements('35')],namedIndividual('#Dry')).
objectPropertyAssertion(objectProperty('#hasSugar'),[namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#VentanaCheninBlanc')],namedIndividual('#OffDry')).
objectPropertyAssertion(objectProperty('#hasSugar'),[namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling'),namedIndividual('#WhitehallLanePrimavera')],namedIndividual('#Sweet')).
objectPropertyAssertion(objectProperty('#hasVintageYear'),namedIndividual('#SaucelitoCanyonZinfandel1998'),namedIndividual('#Year1998')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#CentralTexasRegion'),namedIndividual('#TexasRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#ChiantiRegion'),namedIndividual('#ItalianRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon'),namedIndividual('#SantaCruzMountainsRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#SouthAustraliaRegion'),namedIndividual('#AustralianRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#StGenevieveTexasWhite'),namedIndividual('#CentralTexasRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),namedIndividual('#VentanaCheninBlanc'),namedIndividual('#CentralCoastRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#AlsaceRegion'),namedIndividual('#BeaujolaisRegion'),namedIndividual('#BordeauxRegion'),numberOfElements('5')],namedIndividual('#FrenchRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#AnjouRegion'),namedIndividual('#MuscadetRegion'),namedIndividual('#SancerreRegion'),numberOfElements('4')],namedIndividual('#LoireRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#ArroyoGrandeRegion'),namedIndividual('#CentralCoastRegion'),namedIndividual('#EdnaValleyRegion'),numberOfElements('8')],namedIndividual('#CaliforniaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#BancroftChardonnay'),namedIndividual('#ElyseZinfandel'),namedIndividual('#FormanCabernetSauvignon'),numberOfElements('8')],namedIndividual('#NapaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#CaliforniaRegion'),namedIndividual('#TexasRegion')],namedIndividual('#USRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#CorbansDryWhiteRiesling'),namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#CorbansSauvignonBlanc'),numberOfElements('7')],namedIndividual('#NewZealandRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#CotesDOrRegion'),namedIndividual('#MeursaultRegion')],namedIndividual('#BourgogneRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#CotturiZinfandel'),namedIndividual('#GaryFarrellMerlot'),namedIndividual('#MariettaCabernetSauvignon'),numberOfElements('7')],namedIndividual('#SonomaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#FoxenCheninBlanc'),namedIndividual('#LaneTannerPinotNoir')],namedIndividual('#SantaBarbaraRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#MargauxRegion'),namedIndividual('#PauillacRegion')],namedIndividual('#MedocRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#MedocRegion'),namedIndividual('#SauterneRegion'),namedIndividual('#StEmilionRegion')],namedIndividual('#BordeauxRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),namedIndividual('#MountEdenVineyardEstatePinotNoir')],namedIndividual('#EdnaValleyRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#MountadamChardonnay'),namedIndividual('#MountadamPinotNoir'),namedIndividual('#MountadamRiesling')],namedIndividual('#SouthAustraliaRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#SaucelitoCanyonZinfandel'),namedIndividual('#SaucelitoCanyonZinfandel1998')],namedIndividual('#ArroyoGrandeRegion')).
objectPropertyAssertion(objectProperty('#locatedIn'),[namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling')],namedIndividual('#GermanyRegion')).
objectPropertyAssertion(objectProperty('#madeFromGrape'),namedIndividual('#ChateauDYchemSauterne'),[namedIndividual('#SauvignonBlancGrape'),namedIndividual('#SemillonGrape')]).
classAssertion(class('#Anjou'),namedIndividual('#RoseDAnjou')).
classAssertion(class('#Beaujolais'),namedIndividual('#ChateauMorgonBeaujolais')).
classAssertion(class('#CabernetFranc'),namedIndividual('#WhitehallLaneCabernetFranc')).
classAssertion(class('#CabernetSauvignon'),[namedIndividual('#FormanCabernetSauvignon'),namedIndividual('#MariettaCabernetSauvignon'),namedIndividual('#PageMillWineryCabernetSauvignon'),numberOfElements('4')]).
classAssertion(class('#Chardonnay'),[namedIndividual('#BancroftChardonnay'),namedIndividual('#FormanChardonnay'),namedIndividual('#MountEdenVineyardEdnaValleyChardonnay'),numberOfElements('5')]).
classAssertion(class('#CheninBlanc'),[namedIndividual('#FoxenCheninBlanc'),namedIndividual('#VentanaCheninBlanc')]).
classAssertion(class('#Chianti'),namedIndividual('#ChiantiClassico')).
classAssertion(class('#CotesDOr'),namedIndividual('#ClosDeVougeotCotesDOr')).
classAssertion(class('#DessertWine'),namedIndividual('#WhitehallLanePrimavera')).
classAssertion(class('#DryRiesling'),namedIndividual('#MountadamRiesling')).
classAssertion(class('#IceWine'),namedIndividual('#SelaksIceWine')).
classAssertion(class('#Margaux'),namedIndividual('#ChateauMargaux')).
classAssertion(class('#Meritage'),namedIndividual('#KathrynKennedyLateral')).
classAssertion(class('#Merlot'),[namedIndividual('#GaryFarrellMerlot'),namedIndividual('#LongridgeMerlot')]).
classAssertion(class('#Meursault'),namedIndividual('#ChateauDeMeursaultMeursault')).
classAssertion(class('#Muscadet'),namedIndividual('#SevreEtMaineMuscadet')).
classAssertion(class('#Pauillac'),namedIndividual('#ChateauLafiteRothschildPauillac')).
classAssertion(class('#PetiteSyrah'),[namedIndividual('#MariettaPetiteSyrah'),namedIndividual('#SeanThackreySiriusPetiteSyrah')]).
classAssertion(class('#PinotNoir'),[namedIndividual('#LaneTannerPinotNoir'),namedIndividual('#MountEdenVineyardEstatePinotNoir'),namedIndividual('#MountadamPinotNoir')]).
classAssertion(class('#Port'),namedIndividual('#TaylorPort')).
classAssertion(class('#RedTableWine'),namedIndividual('#MariettaOldVinesRed')).
classAssertion(class('#Region'),[namedIndividual('#AlsaceRegion'),namedIndividual('#AnjouRegion'),namedIndividual('#ArroyoGrandeRegion'),numberOfElements('36')]).
classAssertion(class('#Riesling'),namedIndividual('#CorbansDryWhiteRiesling')).
classAssertion(class('#Sancerre'),namedIndividual('#ClosDeLaPoussieSancerre')).
classAssertion(class('#Sauternes'),namedIndividual('#ChateauDYchemSauterne')).
classAssertion(class('#SauvignonBlanc'),[namedIndividual('#CorbansPrivateBinSauvignonBlanc'),namedIndividual('#CorbansSauvignonBlanc'),namedIndividual('#SelaksSauvignonBlanc'),numberOfElements('4')]).
classAssertion(class('#Semillon'),[namedIndividual('#CongressSpringsSemillon'),namedIndividual('#KalinCellarsSemillon')]).
classAssertion(class('#StEmilion'),namedIndividual('#ChateauChevalBlancStEmilion')).
classAssertion(class('#SweetRiesling'),[namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling'),namedIndividual('#SchlossVolradTrochenbierenausleseRiesling')]).
classAssertion(class('#VintageYear'),namedIndividual('#Year1998')).
classAssertion(class('#WhiteBurgundy'),[namedIndividual('#CortonMontrachetWhiteBurgundy'),namedIndividual('#PulignyMontrachetWhiteBurgundy')]).
classAssertion(class('#WhiteWine'),namedIndividual('#StGenevieveTexasWhite')).
classAssertion(class('#WineBody'),[namedIndividual('#Full'),namedIndividual('#Light'),namedIndividual('#Medium')]).
classAssertion(class('#WineColor'),[namedIndividual('#Red'),namedIndividual('#Rose'),namedIndividual('#White')]).
classAssertion(class('#WineFlavor'),[namedIndividual('#Delicate'),namedIndividual('#Moderate'),namedIndividual('#Strong')]).
classAssertion(class('#WineGrape'),[namedIndividual('#CabernetFrancGrape'),namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#ChardonnayGrape'),numberOfElements('16')]).
classAssertion(class('#WineSugar'),[namedIndividual('#Dry'),namedIndividual('#OffDry'),namedIndividual('#Sweet')]).
classAssertion(class('#Winery'),[namedIndividual('#Bancroft'),namedIndividual('#Beringer'),namedIndividual('#ChateauChevalBlanc'),numberOfElements('43')]).
classAssertion(class('#Zinfandel'),[namedIndividual('#CotturiZinfandel'),namedIndividual('#ElyseZinfandel'),namedIndividual('#MariettaZinfandel'),numberOfElements('5')]).
classAssertion(class('http://www.w3.org/2002/07/owl#Thing'),[namedIndividual('#CabernetFrancGrape'),namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#CheninBlancGrape'),numberOfElements('21')]).
classAssertion([class('http://www.w3.org/2002/07/owl#Thing'),class('#WineGrape')],namedIndividual('#CabernetFrancGrape')).
classAssertion([class('http://www.w3.org/2002/07/owl#Thing'),class('#WineGrape')],namedIndividual('#CabernetSauvignonGrape')).
subClassOf(class('#Anjou'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light')),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Rose')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate')),numberOfElements('4')]).
subClassOf(class('#Beaujolais'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light')),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate')),numberOfElements('5')]).
subClassOf(class('#CabernetFranc'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium')),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate')),numberOfElements('4')]).
subClassOf(class('#CabernetSauvignon'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))]).
subClassOf(class('#CheninBlanc'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))]).
subClassOf(class('#Chianti'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')),numberOfElements('5')]).
subClassOf(class('#DryRiesling'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))]).
subClassOf(class('#Margaux'),[objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate')),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#MerlotGrape'))]).
subClassOf(class('#Medoc'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))]).
subClassOf(class('#Merlot'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))]).
subClassOf(class('#Muscadet'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')),numberOfElements('4')]).
subClassOf(class('#Pauillac'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong')),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape'))]).
subClassOf(class('#PetiteSyrah'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))]).
subClassOf(class('#Port'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet')),numberOfElements('4')]).
subClassOf(class('#RedBurgundy'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotNoirGrape'))).
subClassOf(class('#Sancerre'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#OffDry')),numberOfElements('4')]).
subClassOf(class('#Sauternes'),[objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium')),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#SauterneRegion'))]).
subClassOf(class('#StEmilion'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong')),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape'))]).
subClassOf(class('#Tours'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CheninBlancGrape'))).
subClassOf(class('#WhiteBurgundy'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ChardonnayGrape'))).
subClassOf(class('#Zinfandel'),[objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))]).
subClassOf([class('#Anjou'),class('#Beaujolais'),class('#DryRiesling'),numberOfElements('6')],objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Delicate'))).
subClassOf([class('#Anjou'),class('#Beaujolais'),class('#Muscadet')],objectHasValue(objectProperty('#hasBody'),namedIndividual('#Light'))).
subClassOf([class('#Beaujolais'),class('#CabernetFranc'),class('#CabernetSauvignon'),numberOfElements('11')],objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red'))).
subClassOf([class('#Burgundy'),class('#CabernetSauvignon'),class('#Chianti'),numberOfElements('8')],objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry'))).
subClassOf([class('#CabernetFranc'),class('#CheninBlanc'),class('#Chianti'),numberOfElements('4')],objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Moderate'))).
subClassOf([class('#CabernetFranc'),class('#Sancerre'),class('#Sauternes')],objectHasValue(objectProperty('#hasBody'),namedIndividual('#Medium'))).
subClassOf([class('#Chardonnay'),class('#CheninBlanc'),class('#DryRiesling'),numberOfElements('7')],objectHasValue(objectProperty('#hasColor'),namedIndividual('#White'))).
subClassOf([class('#LateHarvest'),class('#Port')],objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet'))).
subClassOf([class('#Meursault'),class('#Pauillac'),class('#Port'),numberOfElements('4')],objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full'))).
subClassOf([class('#Pauillac'),class('#Port'),class('#StEmilion')],objectHasValue(objectProperty('#hasFlavor'),namedIndividual('#Strong'))).
subClassOf([class('#Pauillac'),class('#StEmilion')],objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape'))).
equivalentClasses(class('#AlsatianWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#AlsaceRegion')))).
equivalentClasses(class('#AmericanWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#USRegion')))).
equivalentClasses(class('#Anjou'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#AnjouRegion')))).
equivalentClasses(class('#Beaujolais'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BeaujolaisRegion')))).
equivalentClasses(class('#Bordeaux'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BordeauxRegion')))).
equivalentClasses(class('#Burgundy'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#BourgogneRegion')))).
equivalentClasses(class('#CaliforniaWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#CaliforniaRegion')))).
equivalentClasses(class('#CotesDOr'),objectIntersectionOf(class('#RedBurgundy'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#CotesDOrRegion')))).
equivalentClasses(class('#DryRiesling'),objectIntersectionOf(class('#Riesling'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')))).
equivalentClasses(class('#FrenchWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#FrenchRegion')))).
equivalentClasses(class('#FullBodiedWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasBody'),namedIndividual('#Full')))).
equivalentClasses(class('#GermanWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#GermanyRegion')))).
equivalentClasses(class('#ItalianWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#ItalianRegion')))).
equivalentClasses(class('#Loire'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#LoireRegion')))).
equivalentClasses(class('#Margaux'),objectIntersectionOf(class('#Medoc'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MargauxRegion')))).
equivalentClasses(class('#Medoc'),objectIntersectionOf(class('#Bordeaux'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MedocRegion')))).
equivalentClasses(class('#Meursault'),objectIntersectionOf(class('#WhiteBurgundy'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MeursaultRegion')))).
equivalentClasses(class('#Muscadet'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#MuscadetRegion')))).
equivalentClasses(class('#Pauillac'),objectIntersectionOf(class('#Medoc'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#PauillacRegion')))).
equivalentClasses(class('#RedTableWine'),objectIntersectionOf(class('#TableWine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')))).
equivalentClasses(class('#RedWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Red')))).
equivalentClasses(class('#RoseWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#Rose')))).
equivalentClasses(class('#Sancerre'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#SancerreRegion')))).
equivalentClasses(class('#StEmilion'),objectIntersectionOf(class('#Bordeaux'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#StEmilionRegion')))).
equivalentClasses(class('#SweetRiesling'),objectIntersectionOf(class('#Riesling'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet')))).
equivalentClasses(class('#SweetWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Sweet')))).
equivalentClasses(class('#TexasWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#TexasRegion')))).
equivalentClasses(class('#Tours'),objectIntersectionOf(class('#Loire'),objectHasValue(objectProperty('#locatedIn'),namedIndividual('#ToursRegion')))).
equivalentClasses(class('#WhiteTableWine'),objectIntersectionOf(class('#TableWine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses(class('#WhiteWine'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses([class('#DryWine'),class('#TableWine')],objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#hasSugar'),namedIndividual('#Dry')))).
subClassOf(class('#CabernetSauvignon'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))]).
subClassOf(class('#Chardonnay'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))]).
subClassOf(class('#CheninBlanc'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry')))]).
subClassOf(class('#DessertWine'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Sweet')))).
subClassOf(class('#IceWine'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))]).
subClassOf(class('#Merlot'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Medium'),namedIndividual('#Light'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Delicate')))]).
subClassOf(class('#PetiteSyrah'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))]).
subClassOf(class('#RedBordeaux'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#MerlotGrape')))).
subClassOf(class('#WhiteBordeaux'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#SemillonGrape'),namedIndividual('#SauvignonBlancGrape')))).
subClassOf(class('#Zinfandel'),[objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'))),objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))]).
subClassOf([class('#CabernetSauvignon'),class('#Chardonnay'),class('#CheninBlanc'),numberOfElements('7')],objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium')))).
subClassOf([class('#CabernetSauvignon'),class('#Chardonnay'),class('#IceWine'),numberOfElements('7')],objectAllValuesFrom(objectProperty('#hasFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Strong')))).
subClassOf([class('#CheninBlanc'),class('#EarlyHarvest')],objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry')))).
subClassOf([class('#Chianti'),class('#DryRiesling'),class('#Merlot')],objectAllValuesFrom(objectProperty('#hasBody'),objectOneOf(namedIndividual('#Medium'),namedIndividual('#Light')))).
subClassOf(class('#Chianti'),class('#ItalianWine')).
subClassOf(class('#Port'),class('#RedWine')).
subClassOf(class('#Sauternes'),[class('#Bordeaux'),class('#LateHarvest')]).
subClassOf(class('#SweetRiesling'),class('#DessertWine')).
subClassOf(class('#Wine'),class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#PotableLiquid')).
subClassOf(class('#WineGrape'),class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#Grape')).
subClassOf([class('#DessertWine'),class('#EarlyHarvest'),class('#LateHarvest')],class('#Wine')).
subClassOf([class('#WineBody'),class('#WineFlavor'),class('#WineSugar')],class('#WineTaste')).
subClassOf([class('#WineColor'),class('#WineTaste')],class('#WineDescriptor')).
equivalentClasses(class('#CabernetFranc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetFrancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CabernetSauvignon'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CabernetSauvignonGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Chardonnay'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ChardonnayGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#CheninBlanc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#CheninBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Gamay'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#GamayGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Merlot'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#MerlotGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#PetiteSyrah'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PetiteSyrahGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#PinotBlanc'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#PinotNoir'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#PinotNoirGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Riesling'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#RieslingGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#SauvignonBlanc'),objectIntersectionOf(class('#SemillonOrSauvignonBlanc'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SauvignonBlancGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Semillon'),objectIntersectionOf(class('#SemillonOrSauvignonBlanc'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#SemillonGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#Zinfandel'),objectIntersectionOf(class('#Wine'),objectHasValue(objectProperty('#madeFromGrape'),namedIndividual('#ZinfandelGrape')),objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
subClassOf([class('#Beaujolais'),class('#Margaux'),class('#Muscadet'),numberOfElements('9')],objectMaxCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
objectPropertyRange(objectProperty('#hasBody'),class('#WineBody')).
objectPropertyRange(objectProperty('#hasColor'),class('#WineColor')).
objectPropertyRange(objectProperty('#hasFlavor'),class('#WineFlavor')).
objectPropertyRange(objectProperty('#hasSugar'),class('#WineSugar')).
objectPropertyRange(objectProperty('#hasVintageYear'),class('#VintageYear')).
objectPropertyRange(objectProperty('#hasWineDescriptor'),class('#WineDescriptor')).
objectPropertyRange(objectProperty('#madeFromGrape'),class('#WineGrape')).
objectPropertyRange([objectProperty('#adjacentRegion'),objectProperty('#locatedIn')],class('#Region')).
equivalentClasses(class('#DryRedWine'),objectIntersectionOf(class('#DryWine'),class('#RedWine'))).
equivalentClasses(class('#DryWhiteWine'),objectIntersectionOf(class('#DryWine'),class('#WhiteWine'))).
equivalentClasses(class('#RedBordeaux'),objectIntersectionOf(class('#Bordeaux'),class('#RedWine'))).
equivalentClasses(class('#RedBurgundy'),objectIntersectionOf(class('#Burgundy'),class('#RedWine'))).
equivalentClasses(class('#WhiteBordeaux'),objectIntersectionOf(class('#Bordeaux'),class('#WhiteWine'))).
equivalentClasses(class('#WhiteBurgundy'),objectIntersectionOf(class('#Burgundy'),class('#WhiteWine'))).
equivalentClasses(class('#WhiteLoire'),objectIntersectionOf(class('#Loire'),class('#WhiteWine'))).
subClassOf(class('#Vintage'),objectExactCardinality('1',objectProperty('#hasVintageYear'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),[objectExactCardinality('1',objectProperty('#hasBody'),class('http://www.w3.org/2002/07/owl#Thing')),objectExactCardinality('1',objectProperty('#hasColor'),class('http://www.w3.org/2002/07/owl#Thing')),objectExactCardinality('1',objectProperty('#hasFlavor'),class('http://www.w3.org/2002/07/owl#Thing')),numberOfElements('5')]).
objectPropertyDomain(objectProperty('#adjacentRegion'),class('#Region')).
objectPropertyDomain(objectProperty('#hasVintageYear'),class('#Vintage')).
objectPropertyDomain(objectProperty('#locatedIn'),class('http://www.w3.org/2002/07/owl#Thing')).
objectPropertyDomain([objectProperty('#hasColor'),objectProperty('#hasWineDescriptor'),objectProperty('#madeFromGrape')],class('#Wine')).
functionalObjectProperty([objectProperty('#hasBody'),objectProperty('#hasColor'),objectProperty('#hasFlavor')]).
subObjectPropertyOf(objectProperty('#madeFromGrape'),objectProperty('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#madeFromFruit')).
subObjectPropertyOf([objectProperty('#hasBody'),objectProperty('#hasColor'),objectProperty('#hasFlavor'),numberOfElements('4')],objectProperty('#hasWineDescriptor')).
differentIndividuals(namedIndividual('#Delicate'),namedIndividual('#Moderate'),namedIndividual('#Strong')).
differentIndividuals(namedIndividual('#Dry'),namedIndividual('#OffDry'),namedIndividual('#Sweet')).
differentIndividuals(namedIndividual('#Full'),namedIndividual('#Light'),namedIndividual('#Medium')).
differentIndividuals(namedIndividual('#Red'),namedIndividual('#Rose'),namedIndividual('#White')).
equivalentClasses(class('#WineBody'),objectOneOf(namedIndividual('#Full'),namedIndividual('#Medium'),namedIndividual('#Light'))).
equivalentClasses(class('#WineColor'),objectOneOf(namedIndividual('#Rose'),namedIndividual('#White'),namedIndividual('#Red'))).
equivalentClasses(class('#WineFlavor'),objectOneOf(namedIndividual('#Moderate'),namedIndividual('#Delicate'),namedIndividual('#Strong'))).
equivalentClasses(class('#WineSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Sweet'),namedIndividual('#Dry'))).
differentIndividuals(namedIndividual('#Dry'),[namedIndividual('#OffDry'),namedIndividual('#Sweet')]).
differentIndividuals([namedIndividual('#Dry'),namedIndividual('#OffDry')],namedIndividual('#Sweet')).
inverseObjectProperties(objectProperty('#madeIntoWine'),objectProperty('#madeFromGrape')).
inverseObjectProperties(objectProperty('#producesWine'),objectProperty('#hasMaker')).
equivalentClasses(class('#SemillonOrSauvignonBlanc'),objectIntersectionOf(class('#Wine'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#SemillonGrape'),namedIndividual('#SauvignonBlancGrape'))))).
equivalentClasses(class('#WhiteNonSweetWine'),objectIntersectionOf(class('#WhiteWine'),objectAllValuesFrom(objectProperty('#hasSugar'),objectOneOf(namedIndividual('#OffDry'),namedIndividual('#Dry'))))).
differentIndividuals(namedIndividual('#Bancroft'),namedIndividual('#ChateauChevalBlanc'),namedIndividual('#ChateauDYchem'),namedIndividual('#ChateauDeMeursault'),namedIndividual('#ChateauLafiteRothschild'),namedIndividual('#ChateauMargauxWinery'),namedIndividual('#ChateauMorgon'),namedIndividual('#ClosDeLaPoussie'),namedIndividual('#ClosDeVougeot'),namedIndividual('#CongressSprings'),namedIndividual('#Corbans'),namedIndividual('#CortonMontrachet'),namedIndividual('#Cotturi'),namedIndividual('#DAnjou'),namedIndividual('#Elyse'),namedIndividual('#Forman'),namedIndividual('#Foxen'),namedIndividual('#GaryFarrell'),namedIndividual('#KalinCellars'),namedIndividual('#KathrynKennedy'),namedIndividual('#LaneTanner'),namedIndividual('#Longridge'),namedIndividual('#Marietta'),namedIndividual('#McGuinnesso'),namedIndividual('#MountEdenVineyard'),namedIndividual('#Mountadam'),namedIndividual('#PageMillWinery'),namedIndividual('#PeterMccoy'),namedIndividual('#PulignyMontrachet'),namedIndividual('#SantaCruzMountainVineyard'),namedIndividual('#SaucelitoCanyon'),namedIndividual('#SchlossRothermel'),namedIndividual('#SchlossVolrad'),namedIndividual('#SeanThackrey'),namedIndividual('#Selaks'),namedIndividual('#SevreEtMaine'),namedIndividual('#StGenevieve'),namedIndividual('#Stonleigh'),namedIndividual('#Taylor'),namedIndividual('#Ventana'),namedIndividual('#WhitehallLane')).
dataPropertyAssertion(dataProperty('#yearValue'),namedIndividual('#Year1998'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#positiveInteger','1998')).
subClassOf(class('#Wine'),objectMinCardinality('1',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing'))).
subClassOf(class('#Wine'),objectSomeValuesFrom(objectProperty('#locatedIn'),class('#Region'))).
subClassOf(class('#WhiteLoire'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#PinotBlancGrape'),namedIndividual('#CheninBlancGrape'),namedIndividual('#SauvignonBlancGrape')))).
subClassOf(class('#Wine'),objectAllValuesFrom(objectProperty('#hasMaker'),class('#Winery'))).
equivalentClasses(class('#Meritage'),objectIntersectionOf(class('#Wine'),objectAllValuesFrom(objectProperty('#madeFromGrape'),objectOneOf(namedIndividual('#CabernetSauvignonGrape'),namedIndividual('#CabernetFrancGrape'),namedIndividual('#PetiteVerdotGrape'),namedIndividual('#MalbecGrape'),namedIndividual('#MerlotGrape'))),objectMinCardinality('2',objectProperty('#madeFromGrape'),class('http://www.w3.org/2002/07/owl#Thing')))).
equivalentClasses(class('#IceWine'),objectIntersectionOf(class('#DessertWine'),class('#LateHarvest'),objectHasValue(objectProperty('#hasColor'),namedIndividual('#White')))).
equivalentClasses(class('#WineDescriptor'),objectUnionOf(class('#WineColor'),class('#WineTaste'))).
disjointClasses(class('#EarlyHarvest'),class('#LateHarvest')).
dataPropertyRange(dataProperty('#yearValue'),datatype('http://www.w3.org/2001/XMLSchema#positiveInteger')).
dataPropertyDomain(dataProperty('#yearValue'),class('#VintageYear')).
transitiveObjectProperty([objectProperty('#locatedIn')]).
symmetricObjectProperty([objectProperty('#adjacentRegion')]).
