class('#AlsatianWine').
class('#AmericanWine').
class('#Anjou').
class('#Beaujolais').
class('#Bordeaux').
class('#Burgundy').
class('#CabernetFranc').
class('#CabernetSauvignon').
class('#CaliforniaWine').
class('#Chardonnay').
class('#CheninBlanc').
class('#Chianti').
class('#CotesDOr').
class('#DessertWine').
class('#DryRedWine').
class('#DryRiesling').
class('#DryWhiteWine').
class('#DryWine').
class('#EarlyHarvest').
class('#FrenchWine').
class('#FullBodiedWine').
class('#Gamay').
class('#GermanWine').
class('#IceWine').
class('#ItalianWine').
class('#LateHarvest').
class('#Loire').
class('#Margaux').
class('#Medoc').
class('#Meritage').
class('#Merlot').
class('#Meursault').
class('#Muscadet').
class('#Pauillac').
class('#PetiteSyrah').
class('#PinotBlanc').
class('#PinotNoir').
class('#Port').
class('#RedBordeaux').
class('#RedBurgundy').
class('#RedTableWine').
class('#RedWine').
class('#Region').
class('#Riesling').
class('#RoseWine').
class('#Sancerre').
class('#Sauternes').
class('#SauvignonBlanc').
class('#Semillon').
class('#SemillonOrSauvignonBlanc').
class('#StEmilion').
class('#SweetRiesling').
class('#SweetWine').
class('#TableWine').
class('#TexasWine').
class('#Tours').
class('#Vintage').
class('#VintageYear').
class('#WhiteBordeaux').
class('#WhiteBurgundy').
class('#WhiteLoire').
class('#WhiteNonSweetWine').
class('#WhiteTableWine').
class('#WhiteWine').
class('#Wine').
class('#WineBody').
class('#WineColor').
class('#WineDescriptor').
class('#WineFlavor').
class('#WineGrape').
class('#WineSugar').
class('#WineTaste').
class('#Winery').
class('#Zinfandel').
class('http://www.w3.org/2002/07/owl#Thing').
class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#Grape').
class('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#PotableLiquid').
dataProperty('#yearValue').
datatype('http://www.w3.org/2001/XMLSchema#positiveInteger').
namedIndividual('#AlsaceRegion').
namedIndividual('#AnjouRegion').
namedIndividual('#ArroyoGrandeRegion').
namedIndividual('#AustralianRegion').
namedIndividual('#Bancroft').
namedIndividual('#BancroftChardonnay').
namedIndividual('#BeaujolaisRegion').
namedIndividual('#Beringer').
namedIndividual('#BordeauxRegion').
namedIndividual('#BourgogneRegion').
namedIndividual('#CabernetFrancGrape').
namedIndividual('#CabernetSauvignonGrape').
namedIndividual('#CaliforniaRegion').
namedIndividual('#CentralCoastRegion').
namedIndividual('#CentralTexasRegion').
namedIndividual('#ChardonnayGrape').
namedIndividual('#ChateauChevalBlanc').
namedIndividual('#ChateauChevalBlancStEmilion').
namedIndividual('#ChateauDYchem').
namedIndividual('#ChateauDYchemSauterne').
namedIndividual('#ChateauDeMeursault').
namedIndividual('#ChateauDeMeursaultMeursault').
namedIndividual('#ChateauLafiteRothschild').
namedIndividual('#ChateauLafiteRothschildPauillac').
namedIndividual('#ChateauMargaux').
namedIndividual('#ChateauMargauxWinery').
namedIndividual('#ChateauMorgon').
namedIndividual('#ChateauMorgonBeaujolais').
namedIndividual('#CheninBlancGrape').
namedIndividual('#ChiantiClassico').
namedIndividual('#ChiantiRegion').
namedIndividual('#ClosDeLaPoussie').
namedIndividual('#ClosDeLaPoussieSancerre').
namedIndividual('#ClosDeVougeot').
namedIndividual('#ClosDeVougeotCotesDOr').
namedIndividual('#CongressSprings').
namedIndividual('#CongressSpringsSemillon').
namedIndividual('#Corbans').
namedIndividual('#CorbansDryWhiteRiesling').
namedIndividual('#CorbansPrivateBinSauvignonBlanc').
namedIndividual('#CorbansSauvignonBlanc').
namedIndividual('#CortonMontrachet').
namedIndividual('#CortonMontrachetWhiteBurgundy').
namedIndividual('#CotesDOrRegion').
namedIndividual('#Cotturi').
namedIndividual('#CotturiZinfandel').
namedIndividual('#DAnjou').
namedIndividual('#Delicate').
namedIndividual('#Dry').
namedIndividual('#EdnaValleyRegion').
namedIndividual('#Elyse').
namedIndividual('#ElyseZinfandel').
namedIndividual('#Forman').
namedIndividual('#FormanCabernetSauvignon').
namedIndividual('#FormanChardonnay').
namedIndividual('#Foxen').
namedIndividual('#FoxenCheninBlanc').
namedIndividual('#FrenchRegion').
namedIndividual('#Full').
namedIndividual('#GamayGrape').
namedIndividual('#GaryFarrell').
namedIndividual('#GaryFarrellMerlot').
namedIndividual('#GermanyRegion').
namedIndividual('#Handley').
namedIndividual('#ItalianRegion').
namedIndividual('#KalinCellars').
namedIndividual('#KalinCellarsSemillon').
namedIndividual('#KathrynKennedy').
namedIndividual('#KathrynKennedyLateral').
namedIndividual('#LaneTanner').
namedIndividual('#LaneTannerPinotNoir').
namedIndividual('#Light').
namedIndividual('#LoireRegion').
namedIndividual('#Longridge').
namedIndividual('#LongridgeMerlot').
namedIndividual('#MalbecGrape').
namedIndividual('#MargauxRegion').
namedIndividual('#Marietta').
namedIndividual('#MariettaCabernetSauvignon').
namedIndividual('#MariettaOldVinesRed').
namedIndividual('#MariettaPetiteSyrah').
namedIndividual('#MariettaZinfandel').
namedIndividual('#McGuinnesso').
namedIndividual('#Medium').
namedIndividual('#MedocRegion').
namedIndividual('#MendocinoRegion').
namedIndividual('#MerlotGrape').
namedIndividual('#MeursaultRegion').
namedIndividual('#Moderate').
namedIndividual('#MountEdenVineyard').
namedIndividual('#MountEdenVineyardEdnaValleyChardonnay').
namedIndividual('#MountEdenVineyardEstatePinotNoir').
namedIndividual('#Mountadam').
namedIndividual('#MountadamChardonnay').
namedIndividual('#MountadamPinotNoir').
namedIndividual('#MountadamRiesling').
namedIndividual('#MuscadetRegion').
namedIndividual('#NapaRegion').
namedIndividual('#NewZealandRegion').
namedIndividual('#OffDry').
namedIndividual('#PageMillWinery').
namedIndividual('#PageMillWineryCabernetSauvignon').
namedIndividual('#PauillacRegion').
namedIndividual('#PeterMccoy').
namedIndividual('#PeterMccoyChardonnay').
namedIndividual('#PetiteSyrahGrape').
namedIndividual('#PetiteVerdotGrape').
namedIndividual('#PinotBlancGrape').
namedIndividual('#PinotNoirGrape').
namedIndividual('#PortugalRegion').
namedIndividual('#PulignyMontrachet').
namedIndividual('#PulignyMontrachetWhiteBurgundy').
namedIndividual('#Red').
namedIndividual('#RieslingGrape').
namedIndividual('#Rose').
namedIndividual('#RoseDAnjou').
namedIndividual('#SancerreRegion').
namedIndividual('#SangioveseGrape').
namedIndividual('#SantaBarbaraRegion').
namedIndividual('#SantaCruzMountainVineyard').
namedIndividual('#SantaCruzMountainVineyardCabernetSauvignon').
namedIndividual('#SantaCruzMountainsRegion').
namedIndividual('#SaucelitoCanyon').
namedIndividual('#SaucelitoCanyonZinfandel').
namedIndividual('#SaucelitoCanyonZinfandel1998').
namedIndividual('#SauterneRegion').
namedIndividual('#SauvignonBlancGrape').
namedIndividual('#SchlossRothermel').
namedIndividual('#SchlossRothermelTrochenbierenausleseRiesling').
namedIndividual('#SchlossVolrad').
namedIndividual('#SchlossVolradTrochenbierenausleseRiesling').
namedIndividual('#SeanThackrey').
namedIndividual('#SeanThackreySiriusPetiteSyrah').
namedIndividual('#Selaks').
namedIndividual('#SelaksIceWine').
namedIndividual('#SelaksSauvignonBlanc').
namedIndividual('#SemillonGrape').
namedIndividual('#SevreEtMaine').
namedIndividual('#SevreEtMaineMuscadet').
namedIndividual('#SonomaRegion').
namedIndividual('#SouthAustraliaRegion').
namedIndividual('#StEmilionRegion').
namedIndividual('#StGenevieve').
namedIndividual('#StGenevieveTexasWhite').
namedIndividual('#Stonleigh').
namedIndividual('#StonleighSauvignonBlanc').
namedIndividual('#Strong').
namedIndividual('#Sweet').
namedIndividual('#Taylor').
namedIndividual('#TaylorPort').
namedIndividual('#TexasRegion').
namedIndividual('#ToursRegion').
namedIndividual('#USRegion').
namedIndividual('#Ventana').
namedIndividual('#VentanaCheninBlanc').
namedIndividual('#White').
namedIndividual('#WhitehallLane').
namedIndividual('#WhitehallLaneCabernetFranc').
namedIndividual('#WhitehallLanePrimavera').
namedIndividual('#Year1998').
namedIndividual('#ZinfandelGrape').
objectProperty('#adjacentRegion').
objectProperty('#hasBody').
objectProperty('#hasColor').
objectProperty('#hasFlavor').
objectProperty('#hasMaker').
objectProperty('#hasSugar').
objectProperty('#hasVintageYear').
objectProperty('#hasWineDescriptor').
objectProperty('#locatedIn').
objectProperty('#madeFromGrape').
objectProperty('#madeIntoWine').
objectProperty('#producesWine').
objectProperty('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#madeFromFruit').
literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#positiveInteger','1998').
