declaration(class(iri='#AlsatianWine')).
declaration(class(iri='#AmericanWine')).
declaration(class(iri='#Anjou')).
declaration(class(iri='#Beaujolais')).
declaration(class(iri='#Bordeaux')).
declaration(class(iri='#Burgundy')).
declaration(class(iri='#CabernetFranc')).
declaration(class(iri='#CabernetSauvignon')).
declaration(class(iri='#CaliforniaWine')).
declaration(class(iri='#Chardonnay')).
declaration(class(iri='#CheninBlanc')).
declaration(class(iri='#Chianti')).
declaration(class(iri='#CotesDOr')).
declaration(class(iri='#DessertWine')).
declaration(class(iri='#DryRedWine')).
declaration(class(iri='#DryRiesling')).
declaration(class(iri='#DryWhiteWine')).
declaration(class(iri='#DryWine')).
declaration(class(iri='#EarlyHarvest')).
declaration(class(iri='#FrenchWine')).
declaration(class(iri='#FullBodiedWine')).
declaration(class(iri='#Gamay')).
declaration(class(iri='#GermanWine')).
declaration(class(iri='#IceWine')).
declaration(class(iri='#ItalianWine')).
declaration(class(iri='#LateHarvest')).
declaration(class(iri='#Loire')).
declaration(class(iri='#Margaux')).
declaration(class(iri='#Medoc')).
declaration(class(iri='#Meritage')).
declaration(class(iri='#Merlot')).
declaration(class(iri='#Meursault')).
declaration(class(iri='#Muscadet')).
declaration(class(iri='#Pauillac')).
declaration(class(iri='#PetiteSyrah')).
declaration(class(iri='#PinotBlanc')).
declaration(class(iri='#PinotNoir')).
declaration(class(iri='#Port')).
declaration(class(iri='#RedBordeaux')).
declaration(class(iri='#RedBurgundy')).
declaration(class(iri='#RedTableWine')).
declaration(class(iri='#RedWine')).
declaration(class(iri='#Region')).
declaration(class(iri='#Riesling')).
declaration(class(iri='#RoseWine')).
declaration(class(iri='#Sancerre')).
declaration(class(iri='#Sauternes')).
declaration(class(iri='#SauvignonBlanc')).
declaration(class(iri='#Semillon')).
declaration(class(iri='#SemillonOrSauvignonBlanc')).
declaration(class(iri='#StEmilion')).
declaration(class(iri='#SweetRiesling')).
declaration(class(iri='#SweetWine')).
declaration(class(iri='#TableWine')).
declaration(class(iri='#TexasWine')).
declaration(class(iri='#Tours')).
declaration(class(iri='#Vintage')).
declaration(class(iri='#VintageYear')).
declaration(class(iri='#WhiteBordeaux')).
declaration(class(iri='#WhiteBurgundy')).
declaration(class(iri='#WhiteLoire')).
declaration(class(iri='#WhiteNonSweetWine')).
declaration(class(iri='#WhiteTableWine')).
declaration(class(iri='#WhiteWine')).
declaration(class(iri='#Wine')).
declaration(class(iri='#WineBody')).
declaration(class(iri='#WineColor')).
declaration(class(iri='#WineDescriptor')).
declaration(class(iri='#WineFlavor')).
declaration(class(iri='#WineGrape')).
declaration(class(iri='#WineSugar')).
declaration(class(iri='#WineTaste')).
declaration(class(iri='#Winery')).
declaration(class(iri='#Zinfandel')).
declaration(dataproperty(iri='#yearValue')).
declaration(objectproperty(iri='#adjacentRegion')).
declaration(objectproperty(iri='#hasBody')).
declaration(objectproperty(iri='#hasColor')).
declaration(objectproperty(iri='#hasFlavor')).
declaration(objectproperty(iri='#hasMaker')).
declaration(objectproperty(iri='#hasSugar')).
declaration(objectproperty(iri='#hasVintageYear')).
declaration(objectproperty(iri='#hasWineDescriptor')).
declaration(objectproperty(iri='#locatedIn')).
declaration(objectproperty(iri='#madeFromGrape')).
declaration(objectproperty(iri='#madeIntoWine')).
declaration(objectproperty(iri='#producesWine')).
functionalobjectproperty(objectproperty(iri='#hasBody')).
functionalobjectproperty(objectproperty(iri='#hasColor')).
functionalobjectproperty(objectproperty(iri='#hasFlavor')).
functionalobjectproperty(objectproperty(iri='#hasMaker')).
functionalobjectproperty(objectproperty(iri='#hasSugar')).
functionalobjectproperty(objectproperty(iri='#hasVintageYear')).
import('http://www.w3.org/TR/2003/PR-owl-guide-20031209/food').
symmetricobjectproperty(objectproperty(iri='#adjacentRegion')).
transitiveobjectproperty(objectproperty(iri='#locatedIn')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#CabernetFrancGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#CabernetSauvignonGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#CheninBlancGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Delicate')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Dry')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Full')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Light')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#MalbecGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Medium')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#MerlotGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Moderate')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#OffDry')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#PetiteVerdotGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#PinotBlancGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Red')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Rose')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#SauvignonBlancGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#SemillonGrape')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Strong')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#Sweet')).
classassertion(class(abbreviatedIRI='owl:Thing'),namedindividual(iri='#White')).
classassertion(class(iri='#Anjou'),namedindividual(iri='#RoseDAnjou')).
classassertion(class(iri='#Beaujolais'),namedindividual(iri='#ChateauMorgonBeaujolais')).
classassertion(class(iri='#CabernetFranc'),namedindividual(iri='#WhitehallLaneCabernetFranc')).
classassertion(class(iri='#CabernetSauvignon'),namedindividual(iri='#FormanCabernetSauvignon')).
classassertion(class(iri='#CabernetSauvignon'),namedindividual(iri='#MariettaCabernetSauvignon')).
classassertion(class(iri='#CabernetSauvignon'),namedindividual(iri='#PageMillWineryCabernetSauvignon')).
classassertion(class(iri='#CabernetSauvignon'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon')).
classassertion(class(iri='#Chardonnay'),namedindividual(iri='#BancroftChardonnay')).
classassertion(class(iri='#Chardonnay'),namedindividual(iri='#FormanChardonnay')).
classassertion(class(iri='#Chardonnay'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay')).
classassertion(class(iri='#Chardonnay'),namedindividual(iri='#MountadamChardonnay')).
classassertion(class(iri='#Chardonnay'),namedindividual(iri='#PeterMccoyChardonnay')).
classassertion(class(iri='#CheninBlanc'),namedindividual(iri='#FoxenCheninBlanc')).
classassertion(class(iri='#CheninBlanc'),namedindividual(iri='#VentanaCheninBlanc')).
classassertion(class(iri='#Chianti'),namedindividual(iri='#ChiantiClassico')).
classassertion(class(iri='#CotesDOr'),namedindividual(iri='#ClosDeVougeotCotesDOr')).
classassertion(class(iri='#DessertWine'),namedindividual(iri='#WhitehallLanePrimavera')).
classassertion(class(iri='#DryRiesling'),namedindividual(iri='#MountadamRiesling')).
classassertion(class(iri='#IceWine'),namedindividual(iri='#SelaksIceWine')).
classassertion(class(iri='#Margaux'),namedindividual(iri='#ChateauMargaux')).
classassertion(class(iri='#Meritage'),namedindividual(iri='#KathrynKennedyLateral')).
classassertion(class(iri='#Merlot'),namedindividual(iri='#GaryFarrellMerlot')).
classassertion(class(iri='#Merlot'),namedindividual(iri='#LongridgeMerlot')).
classassertion(class(iri='#Meursault'),namedindividual(iri='#ChateauDeMeursaultMeursault')).
classassertion(class(iri='#Muscadet'),namedindividual(iri='#SevreEtMaineMuscadet')).
classassertion(class(iri='#Pauillac'),namedindividual(iri='#ChateauLafiteRothschildPauillac')).
classassertion(class(iri='#PetiteSyrah'),namedindividual(iri='#MariettaPetiteSyrah')).
classassertion(class(iri='#PetiteSyrah'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah')).
classassertion(class(iri='#PinotNoir'),namedindividual(iri='#LaneTannerPinotNoir')).
classassertion(class(iri='#PinotNoir'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir')).
classassertion(class(iri='#PinotNoir'),namedindividual(iri='#MountadamPinotNoir')).
classassertion(class(iri='#Port'),namedindividual(iri='#TaylorPort')).
classassertion(class(iri='#RedTableWine'),namedindividual(iri='#MariettaOldVinesRed')).
classassertion(class(iri='#Region'),namedindividual(iri='#AlsaceRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#AnjouRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#ArroyoGrandeRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#AustralianRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#BeaujolaisRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#BordeauxRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#BourgogneRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#CaliforniaRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#CentralCoastRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#CentralTexasRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#ChiantiRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#CotesDOrRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#EdnaValleyRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#FrenchRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#GermanyRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#ItalianRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#LoireRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#MargauxRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#MedocRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#MendocinoRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#MeursaultRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#MuscadetRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#NapaRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#NewZealandRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#PauillacRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#PortugalRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SancerreRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SantaBarbaraRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SantaCruzMountainsRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SauterneRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SonomaRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#SouthAustraliaRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#StEmilionRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#TexasRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#ToursRegion')).
classassertion(class(iri='#Region'),namedindividual(iri='#USRegion')).
classassertion(class(iri='#Riesling'),namedindividual(iri='#CorbansDryWhiteRiesling')).
classassertion(class(iri='#Sancerre'),namedindividual(iri='#ClosDeLaPoussieSancerre')).
classassertion(class(iri='#Sauternes'),namedindividual(iri='#ChateauDYchemSauterne')).
classassertion(class(iri='#SauvignonBlanc'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc')).
classassertion(class(iri='#SauvignonBlanc'),namedindividual(iri='#CorbansSauvignonBlanc')).
classassertion(class(iri='#SauvignonBlanc'),namedindividual(iri='#SelaksSauvignonBlanc')).
classassertion(class(iri='#SauvignonBlanc'),namedindividual(iri='#StonleighSauvignonBlanc')).
classassertion(class(iri='#Semillon'),namedindividual(iri='#CongressSpringsSemillon')).
classassertion(class(iri='#Semillon'),namedindividual(iri='#KalinCellarsSemillon')).
classassertion(class(iri='#StEmilion'),namedindividual(iri='#ChateauChevalBlancStEmilion')).
classassertion(class(iri='#SweetRiesling'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling')).
classassertion(class(iri='#SweetRiesling'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling')).
classassertion(class(iri='#VintageYear'),namedindividual(iri='#Year1998')).
classassertion(class(iri='#WhiteBurgundy'),namedindividual(iri='#CortonMontrachetWhiteBurgundy')).
classassertion(class(iri='#WhiteBurgundy'),namedindividual(iri='#PulignyMontrachetWhiteBurgundy')).
classassertion(class(iri='#WhiteWine'),namedindividual(iri='#StGenevieveTexasWhite')).
classassertion(class(iri='#WineBody'),namedindividual(iri='#Full')).
classassertion(class(iri='#WineBody'),namedindividual(iri='#Light')).
classassertion(class(iri='#WineBody'),namedindividual(iri='#Medium')).
classassertion(class(iri='#WineColor'),namedindividual(iri='#Red')).
classassertion(class(iri='#WineColor'),namedindividual(iri='#Rose')).
classassertion(class(iri='#WineColor'),namedindividual(iri='#White')).
classassertion(class(iri='#WineFlavor'),namedindividual(iri='#Delicate')).
classassertion(class(iri='#WineFlavor'),namedindividual(iri='#Moderate')).
classassertion(class(iri='#WineFlavor'),namedindividual(iri='#Strong')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#CabernetFrancGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#CabernetSauvignonGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#ChardonnayGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#CheninBlancGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#GamayGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#MalbecGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#MerlotGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#PetiteSyrahGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#PetiteVerdotGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#PinotBlancGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#PinotNoirGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#RieslingGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#SangioveseGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#SauvignonBlancGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#SemillonGrape')).
classassertion(class(iri='#WineGrape'),namedindividual(iri='#ZinfandelGrape')).
classassertion(class(iri='#WineSugar'),namedindividual(iri='#Dry')).
classassertion(class(iri='#WineSugar'),namedindividual(iri='#OffDry')).
classassertion(class(iri='#WineSugar'),namedindividual(iri='#Sweet')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Bancroft')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Beringer')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauChevalBlanc')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauDYchem')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauDeMeursault')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauLafiteRothschild')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauMargauxWinery')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ChateauMorgon')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ClosDeLaPoussie')).
classassertion(class(iri='#Winery'),namedindividual(iri='#ClosDeVougeot')).
classassertion(class(iri='#Winery'),namedindividual(iri='#CongressSprings')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Corbans')).
classassertion(class(iri='#Winery'),namedindividual(iri='#CortonMontrachet')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Cotturi')).
classassertion(class(iri='#Winery'),namedindividual(iri='#DAnjou')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Elyse')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Forman')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Foxen')).
classassertion(class(iri='#Winery'),namedindividual(iri='#GaryFarrell')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Handley')).
classassertion(class(iri='#Winery'),namedindividual(iri='#KalinCellars')).
classassertion(class(iri='#Winery'),namedindividual(iri='#KathrynKennedy')).
classassertion(class(iri='#Winery'),namedindividual(iri='#LaneTanner')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Longridge')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Marietta')).
classassertion(class(iri='#Winery'),namedindividual(iri='#McGuinnesso')).
classassertion(class(iri='#Winery'),namedindividual(iri='#MountEdenVineyard')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Mountadam')).
classassertion(class(iri='#Winery'),namedindividual(iri='#PageMillWinery')).
classassertion(class(iri='#Winery'),namedindividual(iri='#PeterMccoy')).
classassertion(class(iri='#Winery'),namedindividual(iri='#PulignyMontrachet')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SantaCruzMountainVineyard')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SaucelitoCanyon')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SchlossRothermel')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SchlossVolrad')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SeanThackrey')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Selaks')).
classassertion(class(iri='#Winery'),namedindividual(iri='#SevreEtMaine')).
classassertion(class(iri='#Winery'),namedindividual(iri='#StGenevieve')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Stonleigh')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Taylor')).
classassertion(class(iri='#Winery'),namedindividual(iri='#Ventana')).
classassertion(class(iri='#Winery'),namedindividual(iri='#WhitehallLane')).
classassertion(class(iri='#Zinfandel'),namedindividual(iri='#CotturiZinfandel')).
classassertion(class(iri='#Zinfandel'),namedindividual(iri='#ElyseZinfandel')).
classassertion(class(iri='#Zinfandel'),namedindividual(iri='#MariettaZinfandel')).
classassertion(class(iri='#Zinfandel'),namedindividual(iri='#SaucelitoCanyonZinfandel')).
classassertion(class(iri='#Zinfandel'),namedindividual(iri='#SaucelitoCanyonZinfandel1998')).
datapropertydomain(dataproperty(iri='#yearValue'),class(iri='#VintageYear')).
datapropertyrange(dataproperty(iri='#yearValue'),datatype(abbreviatedIRI='xsd:positiveInteger')).
differentindividuals(namedindividual(iri='#Dry'),namedindividual(iri='#OffDry')).
differentindividuals(namedindividual(iri='#Dry'),namedindividual(iri='#Sweet')).
differentindividuals(namedindividual(iri='#OffDry'),namedindividual(iri='#Sweet')).
disjointclasses(class(iri='#EarlyHarvest'),class(iri='#LateHarvest')).
equivalentclasses(class(iri='#AlsatianWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#AlsaceRegion')))).
equivalentclasses(class(iri='#AmericanWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#USRegion')))).
equivalentclasses(class(iri='#Anjou'),objectintersectionof(class(iri='#Loire'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#AnjouRegion')))).
equivalentclasses(class(iri='#Beaujolais'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#BeaujolaisRegion')))).
equivalentclasses(class(iri='#Bordeaux'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#BordeauxRegion')))).
equivalentclasses(class(iri='#Burgundy'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#BourgogneRegion')))).
equivalentclasses(class(iri='#CabernetFranc'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CabernetFrancGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#CabernetSauvignon'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CabernetSauvignonGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#CaliforniaWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#CaliforniaRegion')))).
equivalentclasses(class(iri='#Chardonnay'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#ChardonnayGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#CheninBlanc'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CheninBlancGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#CotesDOr'),objectintersectionof(class(iri='#RedBurgundy'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#CotesDOrRegion')))).
equivalentclasses(class(iri='#DryRedWine'),objectintersectionof(class(iri='#DryWine'),class(iri='#RedWine'))).
equivalentclasses(class(iri='#DryRiesling'),objectintersectionof(class(iri='#Riesling'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry')))).
equivalentclasses(class(iri='#DryWhiteWine'),objectintersectionof(class(iri='#DryWine'),class(iri='#WhiteWine'))).
equivalentclasses(class(iri='#DryWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry')))).
equivalentclasses(class(iri='#FrenchWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#FrenchRegion')))).
equivalentclasses(class(iri='#FullBodiedWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Full')))).
equivalentclasses(class(iri='#Gamay'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#GamayGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#GermanWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#GermanyRegion')))).
equivalentclasses(class(iri='#IceWine'),objectintersectionof(class(iri='#DessertWine'),class(iri='#LateHarvest'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White')))).
equivalentclasses(class(iri='#ItalianWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#ItalianRegion')))).
equivalentclasses(class(iri='#Loire'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#LoireRegion')))).
equivalentclasses(class(iri='#Margaux'),objectintersectionof(class(iri='#Medoc'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#MargauxRegion')))).
equivalentclasses(class(iri='#Medoc'),objectintersectionof(class(iri='#Bordeaux'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#MedocRegion')))).
equivalentclasses(class(iri='#Meritage'),objectintersectionof(class(iri='#Wine'),objectallvaluesfrom(objectproperty(iri='#madeFromGrape'),objectoneof(namedindividual(iri='#CabernetSauvignonGrape'),namedindividual(iri='#CabernetFrancGrape'),namedindividual(iri='#PetiteVerdotGrape'),namedindividual(iri='#MalbecGrape'),namedindividual(iri='#MerlotGrape'))),objectmincardinality(cardinality='2',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#Merlot'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#MerlotGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#Meursault'),objectintersectionof(class(iri='#WhiteBurgundy'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#MeursaultRegion')))).
equivalentclasses(class(iri='#Muscadet'),objectintersectionof(class(iri='#Loire'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#MuscadetRegion')))).
equivalentclasses(class(iri='#Pauillac'),objectintersectionof(class(iri='#Medoc'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#PauillacRegion')))).
equivalentclasses(class(iri='#PetiteSyrah'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#PetiteSyrahGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#PinotBlanc'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#PinotBlancGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#PinotNoir'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#PinotNoirGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#RedBordeaux'),objectintersectionof(class(iri='#Bordeaux'),class(iri='#RedWine'))).
equivalentclasses(class(iri='#RedBurgundy'),objectintersectionof(class(iri='#Burgundy'),class(iri='#RedWine'))).
equivalentclasses(class(iri='#RedTableWine'),objectintersectionof(class(iri='#TableWine'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red')))).
equivalentclasses(class(iri='#RedWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red')))).
equivalentclasses(class(iri='#Riesling'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#RieslingGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#RoseWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Rose')))).
equivalentclasses(class(iri='#Sancerre'),objectintersectionof(class(iri='#Loire'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#SancerreRegion')))).
equivalentclasses(class(iri='#SauvignonBlanc'),objectintersectionof(class(iri='#SemillonOrSauvignonBlanc'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#SauvignonBlancGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#Semillon'),objectintersectionof(class(iri='#SemillonOrSauvignonBlanc'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#SemillonGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
equivalentclasses(class(iri='#SemillonOrSauvignonBlanc'),objectintersectionof(class(iri='#Wine'),objectallvaluesfrom(objectproperty(iri='#madeFromGrape'),objectoneof(namedindividual(iri='#SemillonGrape'),namedindividual(iri='#SauvignonBlancGrape'))))).
equivalentclasses(class(iri='#StEmilion'),objectintersectionof(class(iri='#Bordeaux'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#StEmilionRegion')))).
equivalentclasses(class(iri='#SweetRiesling'),objectintersectionof(class(iri='#Riesling'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Sweet')))).
equivalentclasses(class(iri='#SweetWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Sweet')))).
equivalentclasses(class(iri='#TableWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry')))).
equivalentclasses(class(iri='#TexasWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#TexasRegion')))).
equivalentclasses(class(iri='#Tours'),objectintersectionof(class(iri='#Loire'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#ToursRegion')))).
equivalentclasses(class(iri='#WhiteBordeaux'),objectintersectionof(class(iri='#Bordeaux'),class(iri='#WhiteWine'))).
equivalentclasses(class(iri='#WhiteBurgundy'),objectintersectionof(class(iri='#Burgundy'),class(iri='#WhiteWine'))).
equivalentclasses(class(iri='#WhiteLoire'),objectintersectionof(class(iri='#Loire'),class(iri='#WhiteWine'))).
equivalentclasses(class(iri='#WhiteNonSweetWine'),objectintersectionof(class(iri='#WhiteWine'),objectallvaluesfrom(objectproperty(iri='#hasSugar'),objectoneof(namedindividual(iri='#OffDry'),namedindividual(iri='#Dry'))))).
equivalentclasses(class(iri='#WhiteTableWine'),objectintersectionof(class(iri='#TableWine'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White')))).
equivalentclasses(class(iri='#WhiteWine'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White')))).
equivalentclasses(class(iri='#WineBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium'),namedindividual(iri='#Light'))).
equivalentclasses(class(iri='#WineColor'),objectoneof(namedindividual(iri='#Rose'),namedindividual(iri='#White'),namedindividual(iri='#Red'))).
equivalentclasses(class(iri='#WineDescriptor'),objectunionof(class(iri='#WineColor'),class(iri='#WineTaste'))).
equivalentclasses(class(iri='#WineFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Delicate'),namedindividual(iri='#Strong'))).
equivalentclasses(class(iri='#WineSugar'),objectoneof(namedindividual(iri='#OffDry'),namedindividual(iri='#Sweet'),namedindividual(iri='#Dry'))).
equivalentclasses(class(iri='#Zinfandel'),objectintersectionof(class(iri='#Wine'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#ZinfandelGrape')),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape')))).
inverseobjectproperties(objectproperty(iri='#madeIntoWine'),objectproperty(iri='#madeFromGrape')).
inverseobjectproperties(objectproperty(iri='#producesWine'),objectproperty(iri='#hasMaker')).
objectpropertydomain(objectproperty(iri='#adjacentRegion'),class(iri='#Region')).
objectpropertydomain(objectproperty(iri='#hasColor'),class(iri='#Wine')).
objectpropertydomain(objectproperty(iri='#hasVintageYear'),class(iri='#Vintage')).
objectpropertydomain(objectproperty(iri='#hasWineDescriptor'),class(iri='#Wine')).
objectpropertydomain(objectproperty(iri='#locatedIn'),class(abbreviatedIRI='owl:Thing')).
objectpropertydomain(objectproperty(iri='#madeFromGrape'),class(iri='#Wine')).
objectpropertyrange(objectproperty(iri='#adjacentRegion'),class(iri='#Region')).
objectpropertyrange(objectproperty(iri='#hasBody'),class(iri='#WineBody')).
objectpropertyrange(objectproperty(iri='#hasColor'),class(iri='#WineColor')).
objectpropertyrange(objectproperty(iri='#hasFlavor'),class(iri='#WineFlavor')).
objectpropertyrange(objectproperty(iri='#hasSugar'),class(iri='#WineSugar')).
objectpropertyrange(objectproperty(iri='#hasVintageYear'),class(iri='#VintageYear')).
objectpropertyrange(objectproperty(iri='#hasWineDescriptor'),class(iri='#WineDescriptor')).
objectpropertyrange(objectproperty(iri='#locatedIn'),class(iri='#Region')).
objectpropertyrange(objectproperty(iri='#madeFromGrape'),class(iri='#WineGrape')).
prefix(name='BIRNLex_annotation_properties',iri='http://www.nbirn.net/birnlex/1.0/BIRNLex_annotation_properties.owl#').
prefix(name='BuildingsAndPlaces',iri='http://www.ordnancesurvey.co.uk/ontology/BuildingsAndPlaces/v1.1/BuildingsAndPlaces.owl#').
prefix(name='CGO',iri='http://www.comparagrid.org/ontology/CGO.owl#').
prefix(name='Daily',iri='http://cohse.semanticweb.org/ontologies/people#Daily+').
prefix(name='Desktop',iri='file:/C:/Users/Mike/Desktop/').
prefix(name='OBO_annotation_properties',iri='http://www.nbirn.net/birnlex/1.0/OBO_annotation_properties.owl#').
prefix(name='PizzaImportTestA',iri='http://www.co-ode.org/ontologies/PizzaImportTestA.owl#').
prefix(name='Q123',iri='http://cohse.semanticweb.org/ontologies/people#Q123+').
prefix(name='Rabbit',iri='http://www.ordnancesurvey.co.uk/ontology/Rabbit/v1.0/Rabbit.owl#').
prefix(name='SAO',iri='http://ccdb.ucsd.edu/SAO/1.2#').
prefix(name='The',iri='http://cohse.semanticweb.org/ontologies/people#The+').
prefix(name=[],iri='http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#').
prefix(name=ace_lexicon,iri='http://attempto.ifi.uzh.ch/ace_lexicon#').
prefix(name=acetext,iri='http://attempto.ifi.uzh.ch/acetext#').
prefix(name=admin,iri='http://webns.net/mvcb/').
prefix(name=andrea,iri='file:/C:/Users/Mike/Desktop/andrea.rdf#').
prefix(name=animal,iri='http://cohse.semanticweb.org/ontologies/people#animal+').
prefix(name=annotations,iri='http://owl.cs.manchester.ac.uk/explanation/annotations/').
prefix(name=bus,iri='http://cohse.semanticweb.org/ontologies/people#bus+').
prefix(name=cat,iri='http://cohse.semanticweb.org/ontologies/people#cat+').
prefix(name=daml,iri='http://www.daml.org/2001/03/daml+oil#').
prefix(name=dc,iri='http://purl.org/dc/elements/1.1/').
prefix(name=dog,iri='http://cohse.semanticweb.org/ontologies/people#dog+').
prefix(name=employee,iri='http://www.semanticweb.org/ontologies/2009/11/employee.owl#').
prefix(name=ex,iri='http://www.example.org#').
prefix(name=foaf,iri='http://xmlns.com/foaf/0.1/').
prefix(name=foaf2,iri='http://www.ldodds.com/foaf/').
prefix(name=food,iri='http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#').
prefix(name=haulage,iri='http://cohse.semanticweb.org/ontologies/people#haulage+').
prefix(name='j.0',iri='http://owl2.test/rules#').
prefix(name=jms,iri='http://jena.hpl.hp.com/2003/08/jms#').
prefix(name=leigh,iri='mailto:leigh@').
prefix(name=lorry,iri='http://cohse.semanticweb.org/ontologies/people#lorry+').
prefix(name=mad,iri='http://cohse.semanticweb.org/ontologies/people#mad+').
prefix(name=ns0,iri='http://cohse.semanticweb.org/ontologies/people#').
prefix(name=old,iri='http://cohse.semanticweb.org/ontologies/people#old+').
prefix(name=ontology,iri='http://www.mygrid.org.uk/ontology#').
prefix(name=owl,iri='http://www.w3.org/2002/07/owl#').
prefix(name=owl11,iri='http://www.w3.org/2006/12/owl11#').
prefix(name=owl11xml,iri='http://www.w3.org/2006/12/owl11-xml#').
prefix(name=owl2,iri='http://www.w3.org/2006/12/owl2#').
prefix(name=owl2xml,iri='http://www.w3.org/2006/12/owl2-xml#').
prefix(name=p1,iri='http://pervasive.semanticweb.org/ont/2004/01/space#').
prefix(name=p2,iri='http://pervasive.semanticweb.org/ont/2004/01/agent#').
prefix(name=pet,iri='http://cohse.semanticweb.org/ontologies/people#pet+').
prefix(name=photography,iri='http://www.co-ode.org/ontologies/photography/photography.owl#').
prefix(name=photography2,iri='http://www.co-ode.org/ontologies/photography/photography.owl#120').
prefix(name=photography3,iri='http://www.co-ode.org/ontologies/photography/photography.owl#135').
prefix(name=photography4,iri='http://www.co-ode.org/ontologies/photography/photography.owl#4').
prefix(name=photography5,iri='http://www.co-ode.org/ontologies/photography/photography.owl#35').
prefix(name=photography6,iri='http://www.co-ode.org/ontologies/photography/photography.owl#20-100').
prefix(name=photography7,iri='http://www.co-ode.org/ontologies/photography/photography.owl#35-55').
prefix(name=photography8,iri='http://www.co-ode.org/ontologies/photography/photography.owl#18').
prefix(name=photography9,iri='http://www.co-ode.org/ontologies/photography/photography.owl#80').
prefix(name=pizza,iri='http://www.co-ode.org/ontologies/pizza/pizza.owl#').
prefix(name=protege,iri='http://protege.stanford.edu/plugins/owl/protege#').
prefix(name=quality,iri='http://cohse.semanticweb.org/ontologies/people#quality+').
prefix(name=rdf,iri='http://www.w3.org/1999/02/22-rdf-syntax-ns#').
prefix(name=rdfs,iri='http://www.w3.org/2000/01/rdf-schema#').
prefix(name=red,iri='http://cohse.semanticweb.org/ontologies/people#red+').
prefix(name=rss,iri='http://purl.org/rss/1.0/').
prefix(name=skos,iri='http://www.w3.org/2004/02/skos/core#').
prefix(name=sqwrl,iri='http://sqwrl.stanford.edu/ontologies/built-ins/3.4/sqwrl.owl#').
prefix(name=swrl,iri='http://www.w3.org/2003/11/swrl#').
prefix(name=swrla,iri='http://swrl.stanford.edu/ontologies/3.3/swrla.owl#').
prefix(name=swrlb,iri='http://www.w3.org/2003/11/swrlb#').
prefix(name=truck,iri='http://cohse.semanticweb.org/ontologies/people#haulage+truck+').
prefix(name=unnamed,iri='http://www.owl-ontologies.com/unnamed.owl#').
prefix(name=upper,iri='http://www.co-ode.org/ontologies/roberts/upper.owl#').
prefix(name=van,iri='http://cohse.semanticweb.org/ontologies/people#white+van+').
prefix(name=van2,iri='http://cohse.semanticweb.org/ontologies/people#van+').
prefix(name=vcard,iri='http://www.w3.org/2001/vcard-rdf/3.0#').
prefix(name=vin,iri='http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#').
prefix(name=vs,iri='http://www.w3.org/2003/06/sw-vocab-status/ns#').
prefix(name=white,iri='http://cohse.semanticweb.org/ontologies/people#white+').
prefix(name=wot,iri='http://xmlns.com/wot/0.1/').
prefix(name=xml,iri='http://www.w3.org/XML/1998/namespace').
prefix(name=xsd,iri='http://www.w3.org/2001/XMLSchema#').
prefix(name=xsp,iri='http://www.owl-ontologies.com/2005/08/07/xsp.owl#').
subclassof(class(iri='#Anjou'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Light'))).
subclassof(class(iri='#Anjou'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Rose'))).
subclassof(class(iri='#Anjou'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#Anjou'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#OffDry'))).
subclassof(class(iri='#Beaujolais'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Light'))).
subclassof(class(iri='#Beaujolais'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Beaujolais'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#Beaujolais'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Beaujolais'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#GamayGrape'))).
subclassof(class(iri='#Beaujolais'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Burgundy'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#CabernetFranc'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Medium'))).
subclassof(class(iri='#CabernetFranc'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#CabernetFranc'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Moderate'))).
subclassof(class(iri='#CabernetFranc'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#CabernetSauvignon'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#CabernetSauvignon'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#CabernetSauvignon'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#CabernetSauvignon'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Chardonnay'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#Chardonnay'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#Chardonnay'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#CheninBlanc'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#CheninBlanc'),objectallvaluesfrom(objectproperty(iri='#hasSugar'),objectoneof(namedindividual(iri='#OffDry'),namedindividual(iri='#Dry')))).
subclassof(class(iri='#CheninBlanc'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#CheninBlanc'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Moderate'))).
subclassof(class(iri='#Chianti'),class(iri='#ItalianWine')).
subclassof(class(iri='#Chianti'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Medium'),namedindividual(iri='#Light')))).
subclassof(class(iri='#Chianti'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Chianti'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Moderate'))).
subclassof(class(iri='#Chianti'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Chianti'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#ChiantiRegion'))).
subclassof(class(iri='#Chianti'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#SangioveseGrape'))).
subclassof(class(iri='#CotesDOr'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Moderate'))).
subclassof(class(iri='#DessertWine'),class(iri='#Wine')).
subclassof(class(iri='#DessertWine'),objectallvaluesfrom(objectproperty(iri='#hasSugar'),objectoneof(namedindividual(iri='#OffDry'),namedindividual(iri='#Sweet')))).
subclassof(class(iri='#DryRiesling'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Medium'),namedindividual(iri='#Light')))).
subclassof(class(iri='#DryRiesling'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#DryRiesling'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#EarlyHarvest'),class(iri='#Wine')).
subclassof(class(iri='#EarlyHarvest'),objectallvaluesfrom(objectproperty(iri='#hasSugar'),objectoneof(namedindividual(iri='#OffDry'),namedindividual(iri='#Dry')))).
subclassof(class(iri='#IceWine'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#IceWine'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#LateHarvest'),class(iri='#Wine')).
subclassof(class(iri='#LateHarvest'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#LateHarvest'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Sweet'))).
subclassof(class(iri='#Margaux'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#Margaux'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#MerlotGrape'))).
subclassof(class(iri='#Margaux'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Medoc'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Medoc'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Meritage'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Merlot'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Medium'),namedindividual(iri='#Light')))).
subclassof(class(iri='#Merlot'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Delicate')))).
subclassof(class(iri='#Merlot'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Merlot'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Meursault'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Full'))).
subclassof(class(iri='#Muscadet'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Light'))).
subclassof(class(iri='#Muscadet'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#Muscadet'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#Muscadet'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#PinotBlancGrape'))).
subclassof(class(iri='#Muscadet'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Pauillac'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Full'))).
subclassof(class(iri='#Pauillac'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Strong'))).
subclassof(class(iri='#Pauillac'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CabernetSauvignonGrape'))).
subclassof(class(iri='#Pauillac'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#PetiteSyrah'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#PetiteSyrah'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#PetiteSyrah'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#PetiteSyrah'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subclassof(class(iri='#PinotBlanc'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#PinotNoir'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Port'),class(iri='#RedWine')).
subclassof(class(iri='#Port'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Full'))).
subclassof(class(iri='#Port'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Strong'))).
subclassof(class(iri='#Port'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Sweet'))).
subclassof(class(iri='#Port'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#PortugalRegion'))).
subclassof(class(iri='#RedBordeaux'),objectallvaluesfrom(objectproperty(iri='#madeFromGrape'),objectoneof(namedindividual(iri='#CabernetSauvignonGrape'),namedindividual(iri='#MerlotGrape')))).
subclassof(class(iri='#RedBurgundy'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#PinotNoirGrape'))).
subclassof(class(iri='#RedBurgundy'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Riesling'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#Sancerre'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Medium'))).
subclassof(class(iri='#Sancerre'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Delicate'))).
subclassof(class(iri='#Sancerre'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#OffDry'))).
subclassof(class(iri='#Sancerre'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#SauvignonBlancGrape'))).
subclassof(class(iri='#Sancerre'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Sauternes'),class(iri='#Bordeaux')).
subclassof(class(iri='#Sauternes'),class(iri='#LateHarvest')).
subclassof(class(iri='#Sauternes'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Medium'))).
subclassof(class(iri='#Sauternes'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#Sauternes'),objecthasvalue(objectproperty(iri='#locatedIn'),namedindividual(iri='#SauterneRegion'))).
subclassof(class(iri='#SemillonOrSauvignonBlanc'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#SemillonOrSauvignonBlanc'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#White'))).
subclassof(class(iri='#StEmilion'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#StEmilion'),objecthasvalue(objectproperty(iri='#hasFlavor'),namedindividual(iri='#Strong'))).
subclassof(class(iri='#StEmilion'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CabernetSauvignonGrape'))).
subclassof(class(iri='#StEmilion'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#SweetRiesling'),class(iri='#DessertWine')).
subclassof(class(iri='#SweetRiesling'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#SweetRiesling'),objecthasvalue(objectproperty(iri='#hasBody'),namedindividual(iri='#Full'))).
subclassof(class(iri='#Tours'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#CheninBlancGrape'))).
subclassof(class(iri='#Tours'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Vintage'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasVintageYear'))).
subclassof(class(iri='#WhiteBordeaux'),objectallvaluesfrom(objectproperty(iri='#madeFromGrape'),objectoneof(namedindividual(iri='#SemillonGrape'),namedindividual(iri='#SauvignonBlancGrape')))).
subclassof(class(iri='#WhiteBurgundy'),objecthasvalue(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#ChardonnayGrape'))).
subclassof(class(iri='#WhiteBurgundy'),objectmaxcardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#WhiteLoire'),objectallvaluesfrom(objectproperty(iri='#madeFromGrape'),objectoneof(namedindividual(iri='#PinotBlancGrape'),namedindividual(iri='#CheninBlancGrape'),namedindividual(iri='#SauvignonBlancGrape')))).
subclassof(class(iri='#Wine'),class(abbreviatedIRI='food:PotableLiquid')).
subclassof(class(iri='#Wine'),objectallvaluesfrom(objectproperty(iri='#hasMaker'),class(iri='#Winery'))).
subclassof(class(iri='#Wine'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasBody'))).
subclassof(class(iri='#Wine'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasColor'))).
subclassof(class(iri='#Wine'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasFlavor'))).
subclassof(class(iri='#Wine'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasMaker'))).
subclassof(class(iri='#Wine'),objectexactcardinality(cardinality='1',objectproperty(iri='#hasSugar'))).
subclassof(class(iri='#Wine'),objectmincardinality(cardinality='1',objectproperty(iri='#madeFromGrape'))).
subclassof(class(iri='#Wine'),objectsomevaluesfrom(objectproperty(iri='#locatedIn'),class(iri='#Region'))).
subclassof(class(iri='#WineBody'),class(iri='#WineTaste')).
subclassof(class(iri='#WineColor'),class(iri='#WineDescriptor')).
subclassof(class(iri='#WineFlavor'),class(iri='#WineTaste')).
subclassof(class(iri='#WineGrape'),class(abbreviatedIRI='food:Grape')).
subclassof(class(iri='#WineSugar'),class(iri='#WineTaste')).
subclassof(class(iri='#WineTaste'),class(iri='#WineDescriptor')).
subclassof(class(iri='#Zinfandel'),objectallvaluesfrom(objectproperty(iri='#hasBody'),objectoneof(namedindividual(iri='#Full'),namedindividual(iri='#Medium')))).
subclassof(class(iri='#Zinfandel'),objectallvaluesfrom(objectproperty(iri='#hasFlavor'),objectoneof(namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')))).
subclassof(class(iri='#Zinfandel'),objecthasvalue(objectproperty(iri='#hasColor'),namedindividual(iri='#Red'))).
subclassof(class(iri='#Zinfandel'),objecthasvalue(objectproperty(iri='#hasSugar'),namedindividual(iri='#Dry'))).
subobjectpropertyof(objectproperty(iri='#hasBody'),objectproperty(iri='#hasWineDescriptor')).
subobjectpropertyof(objectproperty(iri='#hasColor'),objectproperty(iri='#hasWineDescriptor')).
subobjectpropertyof(objectproperty(iri='#hasFlavor'),objectproperty(iri='#hasWineDescriptor')).
subobjectpropertyof(objectproperty(iri='#hasSugar'),objectproperty(iri='#hasWineDescriptor')).
subobjectpropertyof(objectproperty(iri='#madeFromGrape'),objectproperty(abbreviatedIRI='food:madeFromFruit')).
annotationassertion(annotationproperty(abbreviatedIRI='rdfs:comment'),iri('#WineDescriptor'),literal('Made WineDescriptor unionType of tastes and color')).
annotationassertion(annotationproperty(abbreviatedIRI='rdfs:label'),iri('#Wine'),literal('xml:lang'=en,wine)).
annotationassertion(annotationproperty(abbreviatedIRI='rdfs:label'),iri('#Wine'),literal('xml:lang'=fr,vin)).
datapropertyassertion(dataproperty(iri='#yearValue'),namedindividual(iri='#Year1998'),literal(datatypeIRI='http://www.w3.org/2001/XMLSchema#positiveInteger','1998')).
differentindividuals(namedindividual(iri='#Delicate'),namedindividual(iri='#Moderate'),namedindividual(iri='#Strong')).
differentindividuals(namedindividual(iri='#Dry'),namedindividual(iri='#OffDry'),namedindividual(iri='#Sweet')).
differentindividuals(namedindividual(iri='#Full'),namedindividual(iri='#Light'),namedindividual(iri='#Medium')).
differentindividuals(namedindividual(iri='#Red'),namedindividual(iri='#Rose'),namedindividual(iri='#White')).
objectpropertyassertion(objectproperty(iri='#adjacentRegion'),namedindividual(iri='#MendocinoRegion'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#BancroftChardonnay'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#ChiantiClassico'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CongressSpringsSemillon'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CorbansDryWhiteRiesling'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CorbansSauvignonBlanc'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CortonMontrachetWhiteBurgundy'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#CotturiZinfandel'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#ElyseZinfandel'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#FormanCabernetSauvignon'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#FormanChardonnay'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#FoxenCheninBlanc'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#GaryFarrellMerlot'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#KalinCellarsSemillon'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#KathrynKennedyLateral'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#LaneTannerPinotNoir'),namedindividual(iri='#Light')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#LongridgeMerlot'),namedindividual(iri='#Light')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MariettaCabernetSauvignon'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MariettaOldVinesRed'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MariettaPetiteSyrah'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MariettaZinfandel'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MountadamChardonnay'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MountadamPinotNoir'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#MountadamRiesling'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#PageMillWineryCabernetSauvignon'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#PeterMccoyChardonnay'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#PulignyMontrachetWhiteBurgundy'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SaucelitoCanyonZinfandel'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah'),namedindividual(iri='#Full')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SelaksIceWine'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#SelaksSauvignonBlanc'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#StonleighSauvignonBlanc'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#VentanaCheninBlanc'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#WhitehallLaneCabernetFranc'),namedindividual(iri='#Medium')).
objectpropertyassertion(objectproperty(iri='#hasBody'),namedindividual(iri='#WhitehallLanePrimavera'),namedindividual(iri='#Light')).
objectpropertyassertion(objectproperty(iri='#hasColor'),namedindividual(iri='#SelaksIceWine'),namedindividual(iri='#White')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#BancroftChardonnay'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#ChateauDYchemSauterne'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#ChateauDeMeursaultMeursault'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CongressSpringsSemillon'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CorbansDryWhiteRiesling'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CorbansSauvignonBlanc'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CortonMontrachetWhiteBurgundy'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#CotturiZinfandel'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#ElyseZinfandel'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#FormanCabernetSauvignon'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#FormanChardonnay'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#FoxenCheninBlanc'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#GaryFarrellMerlot'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#KalinCellarsSemillon'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#KathrynKennedyLateral'),namedindividual(iri='#Delicate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#LaneTannerPinotNoir'),namedindividual(iri='#Delicate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#LongridgeMerlot'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MariettaCabernetSauvignon'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MariettaOldVinesRed'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MariettaPetiteSyrah'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MariettaZinfandel'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MountadamChardonnay'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MountadamPinotNoir'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#MountadamRiesling'),namedindividual(iri='#Delicate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#PageMillWineryCabernetSauvignon'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#PeterMccoyChardonnay'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#PulignyMontrachetWhiteBurgundy'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SaucelitoCanyonZinfandel'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah'),namedindividual(iri='#Strong')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SelaksIceWine'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#SelaksSauvignonBlanc'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#StGenevieveTexasWhite'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#StonleighSauvignonBlanc'),namedindividual(iri='#Delicate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#VentanaCheninBlanc'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#WhitehallLaneCabernetFranc'),namedindividual(iri='#Moderate')).
objectpropertyassertion(objectproperty(iri='#hasFlavor'),namedindividual(iri='#WhitehallLanePrimavera'),namedindividual(iri='#Delicate')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#BancroftChardonnay'),namedindividual(iri='#Bancroft')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauChevalBlancStEmilion'),namedindividual(iri='#ChateauChevalBlanc')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauDYchemSauterne'),namedindividual(iri='#ChateauDYchem')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauDeMeursaultMeursault'),namedindividual(iri='#ChateauDeMeursault')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauLafiteRothschildPauillac'),namedindividual(iri='#ChateauLafiteRothschild')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauMargaux'),namedindividual(iri='#ChateauMargauxWinery')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChateauMorgonBeaujolais'),namedindividual(iri='#ChateauMorgon')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ChiantiClassico'),namedindividual(iri='#McGuinnesso')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ClosDeLaPoussieSancerre'),namedindividual(iri='#ClosDeLaPoussie')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ClosDeVougeotCotesDOr'),namedindividual(iri='#ClosDeVougeot')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CongressSpringsSemillon'),namedindividual(iri='#CongressSprings')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CorbansDryWhiteRiesling'),namedindividual(iri='#Corbans')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc'),namedindividual(iri='#Corbans')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CorbansSauvignonBlanc'),namedindividual(iri='#Corbans')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CortonMontrachetWhiteBurgundy'),namedindividual(iri='#CortonMontrachet')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#CotturiZinfandel'),namedindividual(iri='#Cotturi')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#ElyseZinfandel'),namedindividual(iri='#Elyse')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#FormanCabernetSauvignon'),namedindividual(iri='#Forman')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#FormanChardonnay'),namedindividual(iri='#Forman')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#FoxenCheninBlanc'),namedindividual(iri='#Foxen')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#GaryFarrellMerlot'),namedindividual(iri='#GaryFarrell')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#KalinCellarsSemillon'),namedindividual(iri='#KalinCellars')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#KathrynKennedyLateral'),namedindividual(iri='#KathrynKennedy')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#LaneTannerPinotNoir'),namedindividual(iri='#LaneTanner')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#LongridgeMerlot'),namedindividual(iri='#Longridge')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MariettaCabernetSauvignon'),namedindividual(iri='#Marietta')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MariettaOldVinesRed'),namedindividual(iri='#Marietta')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MariettaPetiteSyrah'),namedindividual(iri='#Marietta')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MariettaZinfandel'),namedindividual(iri='#Marietta')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay'),namedindividual(iri='#MountEdenVineyard')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir'),namedindividual(iri='#MountEdenVineyard')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MountadamChardonnay'),namedindividual(iri='#Mountadam')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MountadamPinotNoir'),namedindividual(iri='#Mountadam')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#MountadamRiesling'),namedindividual(iri='#Mountadam')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#PageMillWineryCabernetSauvignon'),namedindividual(iri='#PageMillWinery')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#PeterMccoyChardonnay'),namedindividual(iri='#PeterMccoy')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#PulignyMontrachetWhiteBurgundy'),namedindividual(iri='#PulignyMontrachet')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#RoseDAnjou'),namedindividual(iri='#DAnjou')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon'),namedindividual(iri='#SantaCruzMountainVineyard')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SaucelitoCanyonZinfandel'),namedindividual(iri='#SaucelitoCanyon')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#SaucelitoCanyon')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling'),namedindividual(iri='#SchlossRothermel')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling'),namedindividual(iri='#SchlossVolrad')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah'),namedindividual(iri='#SeanThackrey')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SelaksIceWine'),namedindividual(iri='#Selaks')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SelaksSauvignonBlanc'),namedindividual(iri='#Selaks')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#SevreEtMaineMuscadet'),namedindividual(iri='#SevreEtMaine')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#StGenevieveTexasWhite'),namedindividual(iri='#StGenevieve')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#StonleighSauvignonBlanc'),namedindividual(iri='#Stonleigh')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#TaylorPort'),namedindividual(iri='#Taylor')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#VentanaCheninBlanc'),namedindividual(iri='#Ventana')).
objectpropertyassertion(objectproperty(iri='#hasMaker'),namedindividual(iri='#WhitehallLaneCabernetFranc'),namedindividual(iri='#WhitehallLane')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#BancroftChardonnay'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CongressSpringsSemillon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CorbansDryWhiteRiesling'),namedindividual(iri='#OffDry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CorbansSauvignonBlanc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CortonMontrachetWhiteBurgundy'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#CotturiZinfandel'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#ElyseZinfandel'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#FormanCabernetSauvignon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#FormanChardonnay'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#FoxenCheninBlanc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#GaryFarrellMerlot'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#KalinCellarsSemillon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#KathrynKennedyLateral'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#LaneTannerPinotNoir'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#LongridgeMerlot'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MariettaCabernetSauvignon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MariettaOldVinesRed'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MariettaPetiteSyrah'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MariettaZinfandel'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MountadamChardonnay'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MountadamPinotNoir'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#MountadamRiesling'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#PageMillWineryCabernetSauvignon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#PeterMccoyChardonnay'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#PulignyMontrachetWhiteBurgundy'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SaucelitoCanyonZinfandel'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling'),namedindividual(iri='#Sweet')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling'),namedindividual(iri='#Sweet')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#SelaksSauvignonBlanc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#StGenevieveTexasWhite'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#StonleighSauvignonBlanc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#VentanaCheninBlanc'),namedindividual(iri='#OffDry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#WhitehallLaneCabernetFranc'),namedindividual(iri='#Dry')).
objectpropertyassertion(objectproperty(iri='#hasSugar'),namedindividual(iri='#WhitehallLanePrimavera'),namedindividual(iri='#Sweet')).
objectpropertyassertion(objectproperty(iri='#hasVintageYear'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#Year1998')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#AlsaceRegion'),namedindividual(iri='#FrenchRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#AnjouRegion'),namedindividual(iri='#LoireRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#ArroyoGrandeRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#BancroftChardonnay'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#BeaujolaisRegion'),namedindividual(iri='#FrenchRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#BordeauxRegion'),namedindividual(iri='#FrenchRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#BourgogneRegion'),namedindividual(iri='#FrenchRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CaliforniaRegion'),namedindividual(iri='#USRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CentralCoastRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CentralTexasRegion'),namedindividual(iri='#TexasRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#ChiantiRegion'),namedindividual(iri='#ItalianRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CorbansDryWhiteRiesling'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CorbansPrivateBinSauvignonBlanc'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CorbansSauvignonBlanc'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CotesDOrRegion'),namedindividual(iri='#BourgogneRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#CotturiZinfandel'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#EdnaValleyRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#ElyseZinfandel'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#FormanCabernetSauvignon'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#FormanChardonnay'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#FoxenCheninBlanc'),namedindividual(iri='#SantaBarbaraRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#GaryFarrellMerlot'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#LaneTannerPinotNoir'),namedindividual(iri='#SantaBarbaraRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#LoireRegion'),namedindividual(iri='#FrenchRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#LongridgeMerlot'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MargauxRegion'),namedindividual(iri='#MedocRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MariettaCabernetSauvignon'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MariettaOldVinesRed'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MariettaPetiteSyrah'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MariettaZinfandel'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MedocRegion'),namedindividual(iri='#BordeauxRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MendocinoRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MeursaultRegion'),namedindividual(iri='#BourgogneRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MountEdenVineyardEdnaValleyChardonnay'),namedindividual(iri='#EdnaValleyRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MountEdenVineyardEstatePinotNoir'),namedindividual(iri='#EdnaValleyRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MountadamChardonnay'),namedindividual(iri='#SouthAustraliaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MountadamPinotNoir'),namedindividual(iri='#SouthAustraliaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MountadamRiesling'),namedindividual(iri='#SouthAustraliaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#MuscadetRegion'),namedindividual(iri='#LoireRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#NapaRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#PageMillWineryCabernetSauvignon'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#PauillacRegion'),namedindividual(iri='#MedocRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#PeterMccoyChardonnay'),namedindividual(iri='#SonomaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SancerreRegion'),namedindividual(iri='#LoireRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SantaBarbaraRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SantaCruzMountainVineyardCabernetSauvignon'),namedindividual(iri='#SantaCruzMountainsRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SantaCruzMountainsRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SaucelitoCanyonZinfandel'),namedindividual(iri='#ArroyoGrandeRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SaucelitoCanyonZinfandel1998'),namedindividual(iri='#ArroyoGrandeRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SauterneRegion'),namedindividual(iri='#BordeauxRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SchlossRothermelTrochenbierenausleseRiesling'),namedindividual(iri='#GermanyRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SchlossVolradTrochenbierenausleseRiesling'),namedindividual(iri='#GermanyRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SeanThackreySiriusPetiteSyrah'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SelaksIceWine'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SelaksSauvignonBlanc'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SonomaRegion'),namedindividual(iri='#CaliforniaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#SouthAustraliaRegion'),namedindividual(iri='#AustralianRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#StEmilionRegion'),namedindividual(iri='#BordeauxRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#StGenevieveTexasWhite'),namedindividual(iri='#CentralTexasRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#StonleighSauvignonBlanc'),namedindividual(iri='#NewZealandRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#TexasRegion'),namedindividual(iri='#USRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#ToursRegion'),namedindividual(iri='#LoireRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#VentanaCheninBlanc'),namedindividual(iri='#CentralCoastRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#WhitehallLaneCabernetFranc'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#locatedIn'),namedindividual(iri='#WhitehallLanePrimavera'),namedindividual(iri='#NapaRegion')).
objectpropertyassertion(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#ChateauDYchemSauterne'),namedindividual(iri='#SauvignonBlancGrape')).
objectpropertyassertion(objectproperty(iri='#madeFromGrape'),namedindividual(iri='#ChateauDYchemSauterne'),namedindividual(iri='#SemillonGrape')).
differentindividuals(namedindividual(iri='#Bancroft'),namedindividual(iri='#ChateauChevalBlanc'),namedindividual(iri='#ChateauDYchem'),namedindividual(iri='#ChateauDeMeursault'),namedindividual(iri='#ChateauLafiteRothschild'),namedindividual(iri='#ChateauMargauxWinery'),namedindividual(iri='#ChateauMorgon'),namedindividual(iri='#ClosDeLaPoussie'),namedindividual(iri='#ClosDeVougeot'),namedindividual(iri='#CongressSprings'),namedindividual(iri='#Corbans'),namedindividual(iri='#CortonMontrachet'),namedindividual(iri='#Cotturi'),namedindividual(iri='#DAnjou'),namedindividual(iri='#Elyse'),namedindividual(iri='#Forman'),namedindividual(iri='#Foxen'),namedindividual(iri='#GaryFarrell'),namedindividual(iri='#KalinCellars'),namedindividual(iri='#KathrynKennedy'),namedindividual(iri='#LaneTanner'),namedindividual(iri='#Longridge'),namedindividual(iri='#Marietta'),namedindividual(iri='#McGuinnesso'),namedindividual(iri='#MountEdenVineyard'),namedindividual(iri='#Mountadam'),namedindividual(iri='#PageMillWinery'),namedindividual(iri='#PeterMccoy'),namedindividual(iri='#PulignyMontrachet'),namedindividual(iri='#SantaCruzMountainVineyard'),namedindividual(iri='#SaucelitoCanyon'),namedindividual(iri='#SchlossRothermel'),namedindividual(iri='#SchlossVolrad'),namedindividual(iri='#SeanThackrey'),namedindividual(iri='#Selaks'),namedindividual(iri='#SevreEtMaine'),namedindividual(iri='#StGenevieve'),namedindividual(iri='#Stonleigh'),namedindividual(iri='#Taylor'),namedindividual(iri='#Ventana'),namedindividual(iri='#WhitehallLane')).
